### ISSUE TITLE
Maihog: Did not get front controller from driver.

### ISSUE THREAD

**Issue by cagartner** [weprovide/valet-plus#108]
When I try to access the mailhog domain I receive the default valet error:

Did not get front controller from driver. Please return a front controller to be executed.

Version: Valet+ 1.0.10
Domain: http://mailhog.test/

Can someone help me?

Cheers.

**Comment by samgranger** [comment]
Does mailhog appear to be running? You can check this by using the following command: `brew services ls`

**Comment by jurtjee1997** [comment]
After tje comment `valet db import <filename>` i get the same error `Did not get front controller from driver. Please return a front controller to be executed.`. Any solution?

**Comment by samgranger** [comment]
@jurtjee1997 do you get this error when trying to visit mailhog.test or does this issue occur with one of your projects? If so, what CMS/framework?

**Comment by Neodork** [comment]
Related to https://github.com/weprovide/valet-plus/issues/115.

**Comment by samgranger** [comment]
@jurtjee1997 this sounds like a different issue. Since I haven't received any further updates + assuming @cagartner ran `valet domain test` while running on an older release with the hard coded .dev tld + seeing that @Neodork has added support for custom tld's I'll close this issue. If you are still encountering this issue on our newest release, please feel free to create a new ticket!

**Comment by rogyar** [comment]
This issue occurs also if you specified a wrong domain name in the browser's URL
