### ISSUE TITLE
Xdebug stop on ~/.composer/vendor/weprovide/valet-plus/server.php

### ISSUE THREAD

**Issue by rafaelstz** [weprovide/valet-plus#157]
I'm having this same issue https://github.com/weprovide/valet-plus/issues/150
I would like to know why my PHPStorm is stopping my XDebug on the file `Xdebug stop on ~/.composer/vendor/weprovide/valet-plus/server.php`?
I've tried configuring and not configuring the XDebug on my PHPStorm but doesn't work.

![image](https://user-images.githubusercontent.com/610598/39400948-859f0d06-4b10-11e8-87bd-c9773b3de8c1.png)

**Comment by Neodork** [comment]
Hi @rafaelstz,

Most of the time xDebug stops at `server.php` due to some PHPSTORM settings or lingering breakpoints. Make sure you have the following unchecked within PHPSTORM:

![https://imgur.com/1SPFuwM](https://imgur.com/1SPFuwM.jpg)

Also occasionally your terminal could get stuck within xDebug. You could solve that by upping your connection limit. This is however more of a preference setting:

![https://imgur.com/0HGDsFL](https://imgur.com/0HGDsFL.jpg)

You can find that checkbox within the debug settings:
![https://imgur.com/TE2q6Id](https://imgur.com/TE2q6Id.jpg)

**Comment by rafaelstz** [comment]
Done, thanks! 🙌

**Comment by umarch06** [comment]
@Neodork I followed this all but still it stops at `define('VALET_HOME_PATH', posix_getpwuid(fileowner(__FILE__))['dir'].'/.valet');` statement.

**Comment by nathanjosiah** [comment]
@rafaelstz What did you do to get this fixed?

**Comment by diazwatson** [comment]
Finally got mine to work with these settings:
<img width="1146" alt="Screenshot 2019-04-01 at 23 38 48" src="https://user-images.githubusercontent.com/1080386/55364118-56a70900-54d7-11e9-97c4-a918dddb37b8.png">

<img width="1146" alt="Screenshot 2019-04-01 at 23 40 14" src="https://user-images.githubusercontent.com/1080386/55364201-a4237600-54d7-11e9-8dda-a165e3e0e6d4.png">
domain.test in port 443 without using mapping (same as for localhost)

**Comment by enriquei4** [comment]
> Finally got mine to work with these settings: <img alt="Screenshot 2019-04-01 at 23 38 48" width="1146" src="https://user-images.githubusercontent.com/1080386/55364118-56a70900-54d7-11e9-97c4-a918dddb37b8.png">
> 
> <img alt="Screenshot 2019-04-01 at 23 40 14" width="1146" src="https://user-images.githubusercontent.com/1080386/55364201-a4237600-54d7-11e9-8dda-a165e3e0e6d4.png">
> 
> domain.test in port 443 without using mapping (same as for localhost)

It works!

**Comment by diazwatson** [comment]
Now you owe me a beer @enriquei4 🤣

**Comment by SiluntKnight** [comment]
A side note on this, double check you have `full_page` cache off - this caught me out on a long Friday afternoon 😕
