### ISSUE TITLE
Add Switching from Valet to Valet+ to Read.me/Wiki

### ISSUE THREAD

**Issue by alexkoepke** [weprovide/valet-plus#160]
Sorry if this has been address already but It's not in the Readme or the Wiki.

Is there a suggested path for moving from valet to valet+? Should one uninstall Valet? or is it safe to install valet+ on top of valet?

**Comment by tkrause** [comment]
I recently switched last week, these are the steps I took without issues. All the paths are the same assuming config files haven't been mucked around with. 

First you must unrequire valet with `composer global remove laravel/valet`

Then install valet+ with `composer global add weprovide/valet-plus`

Run `valet fix` (I had to restart my shell to reload the path to valet)

Run `valet install`

**Comment by alexkoepke** [comment]
Thanks! I’ll update if I has success as well.

**Comment by alexkoepke** [comment]
@tkrause I finally got around to trying this out. Unfortunately, it did not go smoothly. I ran into `Uncaught Error: Call to undefined function apcu_fetch()` errors that are documented in #133  and #143 that I was not able to resolve. So now I begin my quest to unbreak my machine which is sad because I really wanted to use this project.

With that said if anyone has any tips I would greatly appreciate it.

**Comment by EHLOVader** [comment]
I too have been getting the apcu_fetch errors and on PHP 7.1 it throws errors about the extensions. PHP 7.2 seems to work fine but ever since homebrew switched to the php@[version] versions and valet broke it hasn't been the same. 

Has anyone fixed this?

**Comment by Neodork** [comment]
Dear Contributor,

With the release of Valet+ `2.0.0` the Valet+ development team and contributors have implemented the [contribution guidelines](https://github.com/weprovide/valet-plus/blob/master/CONTRIBUTING.md#issue-templates). The contribution guidelines aim to improve the support and workflow of Valet+. For further information why this was implemented please check https://github.com/weprovide/valet-plus/issues/393.

We're closing this ticket because it does not follow the correct format. If you feel your ticket is still relevant we encourage you to re-open your ticket using the [correct format](https://github.com/weprovide/valet-plus/issues/new/choose).

Kind regards,
The Valet+ team
