### ISSUE TITLE
not working with envoy

### ISSUE THREAD

**Issue by bsormagec** [weprovide/valet-plus#162]
it has dependency error with envoy can you fix that ?

**Comment by Neodork** [comment]
@bsormagec Could you leave a url for the project so we can find their `composer.json`?

**Comment by Neodork** [comment]
Dear Contributor,

With the release of Valet+ `2.0.0` the Valet+ development team and contributors have implemented the [contribution guidelines](https://github.com/weprovide/valet-plus/blob/master/CONTRIBUTING.md#issue-templates). The contribution guidelines aim to improve the support and workflow of Valet+. For further information why this was implemented please check https://github.com/weprovide/valet-plus/issues/393.

We're closing this ticket because it does not follow the correct format. If you feel your ticket is still relevant we encourage you to re-open your ticket using the [correct format](https://github.com/weprovide/valet-plus/issues/new/choose).

Kind regards,
The Valet+ team

**Comment by CrixuAMG** [comment]
Any update on this issue? Cannot install laravel/envoy on my macbook due to this package's version constraints on symphony/process...

```
 ~ composer global require laravel/envoy -W
Changed current directory to /Users/christian/.composer
Using version ^2.4 for laravel/envoy
./composer.json has been updated
Running composer update laravel/envoy --with-all-dependencies
Loading composer repositories with package information
Updating dependencies
Your requirements could not be resolved to an installable set of packages.

  Problem 1
    - weprovide/valet-plus is locked to version 2.1.0 and an update of this package was not requested.
    - weprovide/valet-plus 2.1.0 requires symfony/process ~2.7|~3.0 -> found symfony/process[v2.7.0, ..., v2.8.52, v3.0.0, ..., v3.4.47] but it conflicts with another require.

Use the option --with-all-dependencies (-W) to allow upgrades, downgrades and removals for packages currently locked to specific versions.
```
