### ISSUE TITLE
Update ElasticSearch stop and start

### ISSUE THREAD

**Issue by tkrause** [weprovide/valet-plus#164]
Currently a very old version of ElasticSearch is the default apparently for magento. 

It would be nice to either be able to select the ElasticSearch version like you can with PHP or work with multiple versions like it does right now with php-fpm.

When I'm out and about, I like to shut down my environment to save on battery life. It would be nice not to have to shutdown ElasticSearch separately.

**Comment by Neodork** [comment]
Brew supports the following elasticsearch versions:

elasticsearch | ✅ | 6.2.4 | Distributed search & analytics engine
elasticsearch@1.7 | ✅ | 1.7.6 | Distributed search & analytics engine
elasticsearch@2.4 | ✅ | 2.4.6 | Distributed search & analytics engine
elasticsearch@5.6 | ✅ | 5.6.9 | Distributed search & analytics engine

Would one of those suffice for Magento?

**Comment by tkrause** [comment]
Based on this issue, 5.x is now supported in Magento.

https://github.com/magento/magento2/issues/13995#issuecomment-384610702

**Comment by samgranger** [comment]
@tkrause I'll look into this - would be nice to be able to switch ES versions like we can switch PHP.

**Comment by Neodork** [comment]
Dear Contributor,

With the release of Valet+ `2.0.0` the Valet+ development team and contributors have implemented the [contribution guidelines](https://github.com/weprovide/valet-plus/blob/master/CONTRIBUTING.md#issue-templates). The contribution guidelines aim to improve the support and workflow of Valet+. For further information why this was implemented please check https://github.com/weprovide/valet-plus/issues/393.

We're closing this ticket because it does not follow the correct format. If you feel your ticket is still relevant we encourage you to re-open your ticket using the [correct format](https://github.com/weprovide/valet-plus/issues/new/choose).

Kind regards,
The Valet+ team
