### ISSUE TITLE
Varnish version

### ISSUE THREAD

**Issue by dkorpar** [weprovide/valet-plus#165]
Valet installs Varnish 6, while only 4 and 5 are supported by Magento 2.
```
$ varnishd -V
varnishd (varnish-6.0.0 revision a068361dff0d25a0d85cf82a6e5fdaf315e06a7d)
```

1. Is there an automated way to define varnish version?
2. Is there an automated way to use Magento varnish configuration?
3. Is there a way to turn it off as it looks that only `install` arg is available?

**Comment by samgranger** [comment]
Hi there,

It looks like the default version of Varnish was updated to version 6 in March. Varnish was added for Neo & Typo3 and I'm not sure what versions they support - I'll have to look deepter into that. What I'd suggest doing is to remove varnish installed by Valet+ and manually install v4 using brew:
`brew remove varnish`
`brew install varnish@4`

In the meantime I will have to think of a more elegant way to support multiple versions of Varnish. Unfortunately this means that for the meantime you have to manually start and stop Varnish using Brew (so not by running `valet varnish on`, but by running `brew services start varnish@4`)

By running `brew services stop varnish@4` you can turn Varnish off.

Magento doesn't use Varnish in the traditional way., when it comes to configuring Magento and Varnish, this guide will be handy: https://support.hypernode.com/knowledgebase/varnish-on-magento2/

Also, make sure to enable the debug headers as described in the guide aboce!

**Comment by dkorpar** [comment]
Thanks for the explanation. I understand it, but I do not get the thing with Varnish as it only gets installed and run as a service.

Entire Valet+ is configured to run on port 80, which is the port that Varnish should listen. What's the idea behind that as all the configurations should be changed and there's a question what other services won't work or upgradeability? Regardless of Magento, shouldn't enabling varnish from Valet take care of those things?

Thanks!

**Comment by toweb7** [comment]
Thank you for comments above how to install varnish@4. Yes, it is required to disable valet varnish and use separately varnish@4.

When I got success to launch varnish@4, by the command like, `sudo varnishd -f <path to varnish file>/default.vcl -a 127.0.0.1:80 -s file,/tmp,500M` wherein the default.vcl I use 
```
backend default {
    .host = "127.0.0.1";
    .port = "8081";
    .first_byte_timeout = 600s;
}
# and other Magento 2 staff
```


I got valet plus error "Valet could not find directory myhost.host:8081" this happens to do to the file https://github.com/weprovide/valet-plus/blob/master/server.php lines 24-28 where we have
```
$siteName = basename(
    // Filter host to support xip.io feature
    $_SERVER['HTTP_HOST'],
    '.'.$valetConfig['domain']
);
```

Because once in the $_SERVER['HTTP_HOST'] you have port like :80 or :8081  basename() starts to work differently. My solution: use above the new line 
`$siteHost = explode(':', $_SERVER['HTTP_HOST'])[0];` and below use already $siteHost

**Comment by karudonaldson** [comment]
Don't mean to raise an old thread but was this ever fully addressed and resolved?  I can't say the documentation explains in great detail what the current state of varnish and/or Redis and if the integrations work out of the box or not, but it doesn't appear to.  

Could you share any feedback perhaps that would be much appreciated?

Thanks :)

**Comment by Neodork** [comment]
Dear Contributor,

With the release of Valet+ `2.0.0` the Valet+ development team and contributors have implemented the [contribution guidelines](https://github.com/weprovide/valet-plus/blob/master/CONTRIBUTING.md#issue-templates). The contribution guidelines aim to improve the support and workflow of Valet+. For further information why this was implemented please check https://github.com/weprovide/valet-plus/issues/393.

We're closing this ticket because it does not follow the correct format. If you feel your ticket is still relevant we encourage you to re-open your ticket using the [correct format](https://github.com/weprovide/valet-plus/issues/new/choose).

Kind regards,
The Valet+ team
