### ISSUE TITLE
Support switching SSL Version from SecureTransport to OpenSSL

### ISSUE THREAD

**Issue by nickbasham** [weprovide/valet-plus#170]
I'm running into issues using WP Migrate Pro to migrate the database from my staging server to my Valet+ local development environment, which seems to be caused by SecureTransport. (See https://deliciousbrains.com/wp-migrate-db-pro/doc/ssl-errors/)

Any chance support for switching to OpenSSL can be added?

Thanks!

**Comment by Neodork** [comment]
Curl seems to also have moved from `homebrew/php` to `homebrew/core`. There seems to be no switching available: https://formulae.brew.sh/formula/curl

Would the linked curl work for you installation? E.G: `brew uninstall curl && brew untap homebrew/php && brew install curl`

**Comment by nickbasham** [comment]
I'm not an expert in brew and compiling/reconfiguring all of this, but I believe curl is being used through the plugin so I think it has to be part of the compiled PHP, and I'm not sure how to or if I can link to Homebrew's curl in PHP.

**Comment by Neodork** [comment]
Dear Contributor,

With the release of Valet+ `2.0.0` the Valet+ development team and contributors have implemented the [contribution guidelines](https://github.com/weprovide/valet-plus/blob/master/CONTRIBUTING.md#issue-templates). The contribution guidelines aim to improve the support and workflow of Valet+. For further information why this was implemented please check https://github.com/weprovide/valet-plus/issues/393.

We're closing this ticket because it does not follow the correct format. If you feel your ticket is still relevant we encourage you to re-open your ticket using the [correct format](https://github.com/weprovide/valet-plus/issues/new/choose).

Kind regards,
The Valet+ team
