### ISSUE TITLE
Disabling xdebug.remote_autostart doesn't work via "valet xdebug"

### ISSUE THREAD

**Issue by wizonesolutions** [weprovide/valet-plus#204]
```
valet xdebug --remote_autostart=0 on
sed: can't read s/xdebug.remote_autostart=1/xdebug.remote_autostart=0/g: No such file or directory
xdebug.remote_autostart is now disabled.
[PECL] Xdebug extension is already enabled!
[php@7.1] Restarting
```

It seems like the `sed` command is failing. I'm not sure which `sed` it's trying to use.

```
which sed
/usr/local/bin/sed
```

^ this is GNU sed from Homebrew. If it is expecting `/usr/bin/sed`, then it ought to manually specify that path, I'd think.

**Comment by wizonesolutions** [comment]
For now, I have just done `brew remove gnu-sed; brew install gnu-sed` to reinstall it with the `g` prefix, which makes `sed` resolve to `/usr/bin/sed`. This works. Perhaps I will do a PR to enforce the proper path later.

**Comment by samgranger** [comment]
A PR would be great!

**Comment by Neodork** [comment]
Dear Contributor,

With the release of Valet+ `2.0.0` the Valet+ development team and contributors have implemented the [contribution guidelines](https://github.com/weprovide/valet-plus/blob/master/CONTRIBUTING.md#issue-templates). The contribution guidelines aim to improve the support and workflow of Valet+. For further information why this was implemented please check https://github.com/weprovide/valet-plus/issues/393.

We're closing this ticket because it does not follow the correct format. If you feel your ticket is still relevant we encourage you to re-open your ticket using the [correct format](https://github.com/weprovide/valet-plus/issues/new/choose).

Kind regards,
The Valet+ team
