### ISSUE TITLE
Broken after switching to php version 5.6

### ISSUE THREAD

**Issue by iugo-robert** [weprovide/valet-plus#209]
## Switching to 5.6

13:16 $ valet use 5.6
Password:
[php@7.1] Unlinking
Unlinking /usr/local/Cellar/php@7.1/7.1.19... 25 symlinks removed

[libjpeg] Relinking
[php@5.6] Linking
Linking /usr/local/Cellar/php@5.6/5.6.36_1... 25 symlinks created

If you need to have this software first in your PATH instead consider running:
  echo 'export PATH="/usr/local/opt/php@5.6/bin:$PATH"' >> ~/.bash_profile
  echo 'export PATH="/usr/local/opt/php@5.6/sbin:$PATH"' >> ~/.bash_profile

[php@5.6] Stopping
[php@7.1] Stopping
[php@7.2] Stopping
PHP Warning:  file_get_contents(): Filename cannot be empty in /Users/robert/.composer/vendor/weprovide/valet-plus/cli/Valet/Filesystem.php on line 112

Warning: file_get_contents(): Filename cannot be empty in /Users/robert/.composer/vendor/weprovide/valet-plus/cli/Valet/Filesystem.php on line 112
PHP Warning:  file_put_contents(): Filename cannot be empty in /Users/robert/.composer/vendor/weprovide/valet-plus/cli/Valet/Filesystem.php on line 125

Warning: file_put_contents(): Filename cannot be empty in /Users/robert/.composer/vendor/weprovide/valet-plus/cli/Valet/Filesystem.php on line 125
PHP Warning:  chown(): No such file or directory in /Users/robert/.composer/vendor/weprovide/valet-plus/cli/Valet/Filesystem.php on line 258

Warning: chown(): No such file or directory in /Users/robert/.composer/vendor/weprovide/valet-plus/cli/Valet/Filesystem.php on line 258
[PECL] Updating PECL channel: pecl.php.net
[PECL] Installing extensions
	apcu is already installed, skipping...
PHP Warning:  file_get_contents(): Filename cannot be empty in /Users/robert/.composer/vendor/weprovide/valet-plus/cli/Valet/Filesystem.php on line 112

Warning: file_get_contents(): Filename cannot be empty in /Users/robert/.composer/vendor/weprovide/valet-plus/cli/Valet/Filesystem.php on line 112
PHP Warning:  file_put_contents(): Filename cannot be empty in /Users/robert/.composer/vendor/weprovide/valet-plus/cli/Valet/Filesystem.php on line 125

Warning: file_put_contents(): Filename cannot be empty in /Users/robert/.composer/vendor/weprovide/valet-plus/cli/Valet/Filesystem.php on line 125
PHP Warning:  chown(): No such file or directory in /Users/robert/.composer/vendor/weprovide/valet-plus/cli/Valet/Filesystem.php on line 258

Warning: chown(): No such file or directory in /Users/robert/.composer/vendor/weprovide/valet-plus/cli/Valet/Filesystem.php on line 258
	apcu successfully enabled
	geoip is already installed, skipping...
PHP Warning:  file_get_contents(): Filename cannot be empty in /Users/robert/.composer/vendor/weprovide/valet-plus/cli/Valet/Filesystem.php on line 112

Warning: file_get_contents(): Filename cannot be empty in /Users/robert/.composer/vendor/weprovide/valet-plus/cli/Valet/Filesystem.php on line 112
PHP Warning:  file_put_contents(): Filename cannot be empty in /Users/robert/.composer/vendor/weprovide/valet-plus/cli/Valet/Filesystem.php on line 125

Warning: file_put_contents(): Filename cannot be empty in /Users/robert/.composer/vendor/weprovide/valet-plus/cli/Valet/Filesystem.php on line 125
PHP Warning:  chown(): No such file or directory in /Users/robert/.composer/vendor/weprovide/valet-plus/cli/Valet/Filesystem.php on line 258

Warning: chown(): No such file or directory in /Users/robert/.composer/vendor/weprovide/valet-plus/cli/Valet/Filesystem.php on line 258
	geoip successfully enabled
[PECL-CUSTOM] Installing extensions
[php@5.6] Restarting
Valet is now using php@5.6

## Confirming php version
13:17 $ php -v
PHP 5.6.36 (cli) (built: Jun 22 2018 00:38:07)
Copyright (c) 1997-2016 The PHP Group
Zend Engine v2.6.0, Copyright (c) 1998-2016 Zend Technologies

## Trying a valet restart (because valet is still running 7.1)
13:17 $ valet restart

Parse error: syntax error, unexpected '?', expecting variable (T_VARIABLE) in /Users/robert/.composer/vendor/symfony/process/Process.php on line 140

**Comment by Neodork** [comment]
Please show me the output of `valet fix`.

**Comment by capitaladot** [comment]
+1

**Comment by guarinogabriel** [comment]
+1

**Comment by mhafizhasan** [comment]
+1

**Comment by cagartner** [comment]
+1

**Comment by cagartner** [comment]
I managed to make it work, in my case, first I needed to go back to 1.0.17 version of valet, because of this issue: #215,

After you rollback the version run `valet fix` and `valet install` to update your valet.

The main problem when you try to change the version is the owner of the folders in `/usr/local/etc/php/` the folders has been created with root owner and not the user #192 , so I used the `chown` command to change the owner:
 
`sudo chown <user> 5.6`

Next I exec the `brew install php@5.6` to reinstall correctly.

Now change the version with valet: `valet use 5.6`, exec the following command printed in cmd to change the version:

```
echo 'export PATH="/usr/local/opt/php@5.6/bin:$PATH"' >> ~/.zshrc
echo 'export PATH="/usr/local/opt/php@5.6/sbin:$PATH"' >> ~/.zshrc
```

And reload the source command: `source ~/.zshrc`

To finish, install the necessaries modules with `valet install`.

So, with this maybe will work correctly.

**Comment by samgranger** [comment]
Could you please try our new 1.0.19 release to see if this solves any of the above issues?

**Comment by capitaladot** [comment]
See related symfony/process error.

**Comment by iugo-robert** [comment]
I tired removing valet with composer and reinstalled it. It now switches to php 5.6 ok.
```
[php@5.6] Restarting
Valet is now using php@5.6
```

However I'm getting a 502 Bad Gateway error. If I look in my nginx logs, its because the valet.sock file does not exist.
```
2018/07/19 11:06:37 [crit] 40971#0: *1 connect() to unix:/Users/robert/.valet/valet.sock failed (2: No such file or directory) while connecting to upstream
```

How do I fix this issue?

**Comment by Neodork** [comment]
Dear Contributor,

With the release of Valet+ `2.0.0` the Valet+ development team and contributors have implemented the [contribution guidelines](https://github.com/weprovide/valet-plus/blob/master/CONTRIBUTING.md#issue-templates). The contribution guidelines aim to improve the support and workflow of Valet+. For further information why this was implemented please check https://github.com/weprovide/valet-plus/issues/393.

We're closing this ticket because it does not follow the correct format. If you feel your ticket is still relevant we encourage you to re-open your ticket using the [correct format](https://github.com/weprovide/valet-plus/issues/new/choose).

Kind regards,
The Valet+ team
