### ISSUE TITLE
phpRedisAdmin and friends

### ISSUE THREAD

**Issue by agjmills** [weprovide/valet-plus#221]
I recently had to do some development using redis and found phpRedisAdmin very useful

I considered doing the work and opening a PR to include phpRedisAdmin with valet plus but I wanted to know other peoples thoughts on it before I started

You could class phpRedisAdmin as similar to MailHog - included as a service that is useful to aid development - but on the other side of the coin, where do you stop? Do you include phpMyAdmin, ElasticSearch HEAD etc too? 

I'd like to know what everyone else thinks before committing to adding it

If the consensus is to include it, I'd be happy to include phpMyAdmin and whatever else you would find useful, too - feel free to add comments and recommendations

**Comment by SanderAtom** [comment]
I think the aim of Valet+ is to provide a rich set of tools for development and the set is different for each developer, so I don't think it's a problem to have Sequel Pro and phpMyAdmin as alternatives to use (I miss phpMyAdmins search functionality in Sequel Pro) . Also phpRedisAdmin could be useful I think, didn't use it yet.

**Comment by Neodork** [comment]
Dear Contributor,

With the release of Valet+ `2.0.0` the Valet+ development team and contributors have implemented the [contribution guidelines](https://github.com/weprovide/valet-plus/blob/master/CONTRIBUTING.md#issue-templates). The contribution guidelines aim to improve the support and workflow of Valet+. For further information why this was implemented please check https://github.com/weprovide/valet-plus/issues/393.

We're closing this ticket because it does not follow the correct format. If you feel your ticket is still relevant we encourage you to re-open your ticket using the [correct format](https://github.com/weprovide/valet-plus/issues/new/choose).

Kind regards,
The Valet+ team
