### ISSUE TITLE
Xdebug is very slow

### ISSUE THREAD

**Issue by JosephMaxwell** [weprovide/valet-plus#224]
I am using Valet+ to work on Magento 2 projects. As much as I have been liking the idea of Valet+ (and moving from Vagrant to Valet+), I am up against a problem that I am unsure of how to solve.

Valet+ with xdebug enabled is _very_ slow. It is slower than Vagrant without PHPStorm connected to xdebug (10-12 seconds to render a cached page). But, on Valet+, with PHPStorm connected to xdebug, it is 6-7 times slower (40-60 seconds).

I am using a late-model MacBook Pro with 16GB RAM and a solid state drive. I have uninstalled and reinstalled Valet+ as well as searched for any optimization technique I can figure out to make xdebug perform faster.

Am I missing something? What can I share that would be helpful in troubleshooting this?

Thank you for your time.

**Comment by samgranger** [comment]
I have seen this on multiple occasions so it's not just your setup. Any help debugging this issue is more than welcome. What Magento caches do you have turned on/off by the way?

**Comment by JosephMaxwell** [comment]
Hi Sam, thanks for your feedback. I'm glad to know that I am not alone here. I have spent quite a few hours looking into it with no success. Like the apcu issue, I'm sure it's something easy.

I have the `full_page` and `block_html` caches off for the above information.

My gut suspicion is that there is a bottleneck in port traffic. That said, PHP is running on a socket, which shouldn't have any bottleneck. 12-13 seconds seems way too slow for PHP and that is exasperated when turning on xdebug.

I have the Mac firewall turned off and disabled and uninstalled almost everything else. 

* Would it be helpful to try running PHP-FPM on a port instead of a socket?
* Are you aware of any way to log these types of interactions?

**Comment by samgranger** [comment]
Could you possibly share your phpinfo() output?

Re: your last 2 points, I'm not 100% sure at the moment. Will need to investigate further.

**Comment by JosephMaxwell** [comment]
I did some more investigation, comparing vagrant with valet plus.

Xdebug on: 30s (vagrant), 60+s (valet plus)
Xdebug off: 21s (vagrant), 22s (valet plus)

I am seeing that there is some horribly unoptimized code in the theme for this project, so that is contributing to the length of time.

Here is the phpinfo:
https://gist.github.com/JosephMaxwell/8cd6b766df9350f6aac9cfd4e60c57e8

**Comment by samgranger** [comment]
Thanks for the additional info. Will continue to try and debug this issue.

**Comment by SanderAtom** [comment]
Any difference turning `block_html` caching on as well?

**Comment by JosephMaxwell** [comment]
@SanderAtom Thanks for checking. Yes, `block_html` helps a lot. That is because the call stack is much smaller due to the caching. If I am making changes to the block and have `block_html` on, I have to refresh that every time, which becomes the equivalent of leaving it off.

The issue seems to be that xdebug take 3x or longer to process a line of PHP rather than having it off. Is that normal?

My thought is that it isn't normal considering vagrant runs so much faster than Valet with xdebug on.

**Comment by SanderAtom** [comment]
Are you listening for debug connections all the time, so is the button green in PhpStorm?
![image](https://user-images.githubusercontent.com/30903591/42766734-87fbc1e0-891b-11e8-85aa-35c36d411940.png)
That degrades the performance significantly.

**Comment by samgranger** [comment]
Are you using the vagrant setup are you using? That way, I can maybe compare - possibly it's a different setting somewhere that might help.

**Comment by JosephMaxwell** [comment]
Hello @samgranger. Sorry for the delay here.

[Here is my `php -i` from vagrant.](https://gist.github.com/JosephMaxwell/bf8ddc09b99217831ed5eb37835a29d8) We use a custom setup so it's not something that easy to replicate.

I really appreciate your help on this.

**Comment by sajidunnar** [comment]
Is there a way that we can disbale xdebug for shell ?

I dont know if we can run some command in valet plus ?
https://medium.com/@chrisloftus/how-to-disable-xdebug-with-php-7-cli-ubuntu-fd42360bafb7

**Comment by oroskodias** [comment]
Experiencing the same problem...
MacOS Mojave 10.14 (18A391), Valet+ 1.0.21
XDebug is extremelly slow...

**Comment by gsomoza** [comment]
I think ValetPlus will always run slower XDebug than Vagrant simply because of the extra PHP stack (server.php) that runs on top of every single request. The question is how much slower: 3x definitely seems excessive.

@JosephMaxwell are your timings based on TTFB for main page? Or are they total render time including AJAX, etc? 20+ seconds with XDebug off is definitely still too high, so there must be something else wrong with your config, and then probably xdebug is just making that thing "worse".

For reference I'm running complex M2 projects in under 5 seconds TTFB with xdebug disabled on a top-spec mid-2018 MBP. I haven't tested how much slower it is with XDebug simply cause it seems "acceptably slow" for me ATM :)

**Comment by Neodork** [comment]
Dear Contributor,

With the release of Valet+ `2.0.0` the Valet+ development team and contributors have implemented the [contribution guidelines](https://github.com/weprovide/valet-plus/blob/master/CONTRIBUTING.md#issue-templates). The contribution guidelines aim to improve the support and workflow of Valet+. For further information why this was implemented please check https://github.com/weprovide/valet-plus/issues/393.

We're closing this ticket because it does not follow the correct format. If you feel your ticket is still relevant we encourage you to re-open your ticket using the [correct format](https://github.com/weprovide/valet-plus/issues/new/choose).

Kind regards,
The Valet+ team
