### ISSUE TITLE
Server variable documentation

### ISSUE THREAD

**Issue by samgranger** [weprovide/valet-plus#225]
Add documentation for https://github.com/weprovide/valet-plus/commit/5038391c26ef07b4d31976882d7710d66dd5c012

Taken from @MartinPeverelli

A quick example - `.env.valet`:

```
<?php

return [
    'website1' => [
        'MAGE_RUN_CODE' => 'usa',
        'MAGE_RUN_TYPE' => 'website',
    ],
    'website2' => [
        'MAGE_RUN_CODE' => 'arg',
        'MAGE_RUN_TYPE' => 'website',
    ],
];
```

The idea is quite simple: the file will be read by the Valet Driver, and if the top level key matches the requested site, then the key-value pairs inside will be loaded as server environment variables.

In the example above, when website1.dev is requested, then this will be loaded:

$_SERVER['MAGE_RUN_CODE`] === 'usa' // true
$_SERVER['MAGE_RUN_TYPE`] === 'website' // true

**Comment by lazyguru** [comment]
FYI, this also allows for some more advanced stuff like:

```
// Get host from header
$host = $_SERVER['HTTP_HOST'];
if (isset($_SERVER['HTTP_X_FORWARDED_HOST'])) {
    // Get host from X_FORWARDED header. Usually happens when behind ngrok
    $host = $_SERVER['HTTP_X_FORWARDED_HOST'];
    // Override original host header. I forget if it is Valet or Magento that has a problem otherwise
    $_SERVER['HTTP_HOST'] = $host;
}
// Below regex looks for http://example.dev/us/ and extracts the "us" part to use as MAGE_RUN_CODE
if (preg_match('/^\/([a-z]{2})\/(.*)/', $_SERVER['REQUEST_URI'], $matches)) {
    return [
        $host => [  // Use $host as array key to avoid having to hard-code hostnames into array
            'MAGE_RUN_TYPE' => 'website',
            'MAGE_RUN_CODE' => $matches[1]
        ]
    ];
}
```

With the above, I can copy the same file into multiple installations and not have to updated it for the new host.  Even better is using a symlink to a master copy 😄

**Comment by Leland** [comment]
It would be nice to automatically use `magento-vars.php` for Magento 2, which serves the same purpose.

**Comment by Zakini** [comment]
`laravel/valet` changed the file name to `.valet-env.php` and also added support for a `'*'` key that sets vars on all sites. Can these changes be pulled in or the docs updated to highlight the differences with valet and valet-plus?

**Comment by Neodork** [comment]
Dear Contributor,

With the release of Valet+ `2.0.0` the Valet+ development team and contributors have implemented the [contribution guidelines](https://github.com/weprovide/valet-plus/blob/master/CONTRIBUTING.md#issue-templates). The contribution guidelines aim to improve the support and workflow of Valet+. For further information why this was implemented please check https://github.com/weprovide/valet-plus/issues/393.

We're closing this ticket because it does not follow the correct format. If you feel your ticket is still relevant we encourage you to re-open your ticket using the [correct format](https://github.com/weprovide/valet-plus/issues/new/choose).

Kind regards,
The Valet+ team
