### ISSUE TITLE
Nginx is not setting server name for Xdebug, breaking PhpStorm

### ISSUE THREAD

**Issue by capitaladot** [weprovide/valet-plus#228]
See: https://stackoverflow.com/questions/23344106/php-storm-debugging-creates-empty-server-definitions

Short story is, nginx ends up reporting a blank host name, which causes PhpStorm to fail to map the Php Server (its term) for Xdebug, and PhpStorm then creates a blank unusable, unsaveable entry, all of which breaks step debugging and the ability to use breakpoints. 

It looks like we need a nginx server variable?

**Comment by samgranger** [comment]
Indeed, we have solved this in some drivers, for example: https://github.com/weprovide/valet-plus/blob/master/cli/drivers/Magento2ValetDriver.php#L137

Solving it in NGINX would indeed be more elegant, I'll look into using `fastcgi_param SERVER_NAME $host;` - thanks for the link!

**Comment by Neodork** [comment]
Dear Contributor,

With the release of Valet+ `2.0.0` the Valet+ development team and contributors have implemented the [contribution guidelines](https://github.com/weprovide/valet-plus/blob/master/CONTRIBUTING.md#issue-templates). The contribution guidelines aim to improve the support and workflow of Valet+. For further information why this was implemented please check https://github.com/weprovide/valet-plus/issues/393.

We're closing this ticket because it does not follow the correct format. If you feel your ticket is still relevant we encourage you to re-open your ticket using the [correct format](https://github.com/weprovide/valet-plus/issues/new/choose).

Kind regards,
The Valet+ team
