### ISSUE TITLE
Can only install one of: symfony/process

### ISSUE THREAD

**Issue by webfolkcreative** [weprovide/valet-plus#230]
I know there's been several topics opened for the symfony/process update because it has caused conflicts for people using php 5.6. Is there a ETA on when we can expect Valet+ to support symfony/process ~4?

Thanks!

Note: Conflict coming from laravel/installer.

**Comment by samgranger** [comment]
I wasn't sure on how to solve this - still don't know the best way, the main thing is, is that I do not want to drop the 5.6 support - that has a bigger priority over conflicts with Laravel in my eyes. One solution I am contemplating is to clone the `symfony/process` package completely to `weprovide/valet-plus-process` for example. Does anyone have a more elegant solution for this issue? Because my solution feels a little dirty.

**Comment by webfolkcreative** [comment]
Yeah, I totally get not wanting to drop 5.6 support. Unfortunately, I don't have a "better" solution. Seems symfony/process ~4 doesn't support php 5.6 at all, so this situation kind of sucks.

**Comment by tenyard** [comment]
Easiest fix currently is to nuke your composer global setup (~/.composer/composer.json and the vendor folder) then install valet-plus globally FIRST

this will install process 3.* which the laravel-installer will happily use.

you can then add back your other dependencies and deal with those fun and games on your own :)

**Comment by Neodork** [comment]
Dear Contributor,

With the release of Valet+ `2.0.0` the Valet+ development team and contributors have implemented the [contribution guidelines](https://github.com/weprovide/valet-plus/blob/master/CONTRIBUTING.md#issue-templates). The contribution guidelines aim to improve the support and workflow of Valet+. For further information why this was implemented please check https://github.com/weprovide/valet-plus/issues/393.

We're closing this ticket because it does not follow the correct format. If you feel your ticket is still relevant we encourage you to re-open your ticket using the [correct format](https://github.com/weprovide/valet-plus/issues/new/choose).

Kind regards,
The Valet+ team
