### ISSUE TITLE
FR: possibility to add a TLD domain

### ISSUE THREAD

**Issue by mischabraam** [weprovide/valet-plus#236]
With `valet domain` it's possible to change the TLD for all dev websites. I have a couple of websites which are multi language depending on the TLD. So I'd like to add different TLDs besides the default `.test`, for example `.best` or `.dest`.

**Comment by SanderAtom** [comment]
I think you can get unexpected results since for instance `.best` is an existing TLD.
So you have a multilingual website? Can you not use a `.env.valet` like this https://github.com/weprovide/valet-plus/issues/225 and have domains like `domain.nl.test`, `domain.com.test`, or does it have to be a TLD?

**Comment by mischabraam** [comment]
Not sure, didn't try that. I'll give it a go.

**Comment by philiprabbett** [comment]
Is it possible with Valet+ to have multiple domains such as `.test` and `.loc` for example and link specific sites to specific domains?

I'm not sure if it's still possible but according to this article, it used to be with the original Valet.

https://medium.com/@basantbesra/adding-multiple-tlds-in-valet-b8bc1c60155e

**Comment by SanderAtom** [comment]
You could try that, the file is here: `~/.valet/dnsmasq.conf`.

**Comment by Neodork** [comment]
Dear Contributor,

With the release of Valet+ `2.0.0` the Valet+ development team and contributors have implemented the [contribution guidelines](https://github.com/weprovide/valet-plus/blob/master/CONTRIBUTING.md#issue-templates). The contribution guidelines aim to improve the support and workflow of Valet+. For further information why this was implemented please check https://github.com/weprovide/valet-plus/issues/393.

We're closing this ticket because it does not follow the correct format. If you feel your ticket is still relevant we encourage you to re-open your ticket using the [correct format](https://github.com/weprovide/valet-plus/issues/new/choose).

Kind regards,
The Valet+ team
