### ISSUE TITLE
PECL [DomainException] when installing Valet

### ISSUE THREAD

**Issue by n1smo** [weprovide/valet-plus#243]
Hi im getting following error, when trying to installing vallet. Any ideas how to fix this?

`
...
[PECL] Updating PECL channel: pecl.php.net
[PECL] Installing extensions
[DomainException]
  Could not find installation path for: apcu_bc
  downloading apcu_bc-1.0.4.tgz ...
  Starting to download apcu_bc-1.0.4.tgz (7,406 bytes)
  .....done: 7,406 bytes
  downloading apcu-5.1.12.tgz ...
  Starting to download apcu-5.1.12.tgz (105,890 bytes)
  ...done: 105,890 bytes
  39 source files, building
  running: phpize
  Configuring for:
  PHP Api Version:         20160303
  Zend Module Api No:      20160303
  Zend Extension Api No:   320160303
  sh: fork: Resource temporarily unavailable
  autom4te: need GNU m4 1.4 or later: /usr/bin/m4
  autoheader: '/usr/local/Cellar/autoconf/2.69/bin/autom4te' failed with exit
   status: 1
  ERROR: `phpize' failed`

**Comment by SanderAtom** [comment]
Does it still fail? Looks like a temporary error: `Resource temporarily unavailable`

**Comment by walkerdigital** [comment]
I'm still getting this error.

**Comment by n1smo** [comment]
Yeah, seems to be fixed now, thanks!

**Comment by SanderAtom** [comment]
@walkerdigital can you post the error message?

**Comment by Neodork** [comment]
Dear Contributor,

With the release of Valet+ `2.0.0` the Valet+ development team and contributors have implemented the [contribution guidelines](https://github.com/weprovide/valet-plus/blob/master/CONTRIBUTING.md#issue-templates). The contribution guidelines aim to improve the support and workflow of Valet+. For further information why this was implemented please check https://github.com/weprovide/valet-plus/issues/393.

We're closing this ticket because it does not follow the correct format. If you feel your ticket is still relevant we encourage you to re-open your ticket using the [correct format](https://github.com/weprovide/valet-plus/issues/new/choose).

Kind regards,
The Valet+ team
