### ISSUE TITLE
Setting password for root user failed.

### ISSUE THREAD

**Issue by ericswansonfc** [weprovide/valet-plus#246]
Every time I run Valet Install i get the following error: Setting password for root user failed. Here is my brew services list:

<img width="1042" alt="screen shot 2018-09-12 at 3 31 03 pm" src="https://user-images.githubusercontent.com/43220612/45451488-de930600-b6a0-11e8-9c2d-df11d42d178c.png">

**Comment by tiikeri86** [comment]
I have the same issue even I run valet with sudo

**Comment by SanderAtom** [comment]
Can you connect to MySQL? Did you have any MySQL installed before installing Valet+?

**Comment by toptomatotwo** [comment]
Try running `which mysql`.
if this returns empty as mine did, the following fix may work
```
brew uninstall --force mysql

**Comment by MikeiLL** [comment]
It looks like `valet install` installs mysql@5.7, whereas `brew install mysql` installs mysql@8.

Not sure though because the installation output looks like this:

```
[mysql@5.7] Stopping
[mysql@5.7] Configuring
[mysql@5.7] Restarting
```

But `/usr/local/Cellar/mysql/` just contains `8.0.12`.

**Comment by sirugh** [comment]
@toptomatotwo's solution worked for me!

**Comment by TheRealJAG** [comment]
I'm getting the same error on OSX 10.14 Is this a permission issue?

<img width="711" alt="Screen Shot 2019-03-27 at 8 06 56 PM" src="https://user-images.githubusercontent.com/4411961/55126984-e4e05100-50cb-11e9-8bf5-8030b3ad2f07.png">

**Comment by MikeiLL** [comment]
@TheRealJAG Did you confirm which version of MySQL you are using? See the above entries about that in terms of the Homebrew-installed MySQL version.

**Comment by TheRealJAG** [comment]
@MikeiLL Here is what I found. 

MacBook-Pro:~ jgonzalez$ brew info mysql
mysql: stable 8.0.15 (bottled)
Open source relational database management system
https://dev.mysql.com/doc/refman/8.0/en/
Conflicts with:
  mariadb (because mysql, mariadb, and percona install the same binaries.)
  mariadb-connector-c (because both install plugins)
  mysql-cluster (because mysql, mariadb, and percona install the same binaries.)
  mysql-connector-c (because both install MySQL client libraries)
  percona-server (because mysql, mariadb, and percona install the same binaries.)
Not installed
From: https://github.com/Homebrew/homebrew-core/blob/master/Formula/mysql.rb
==> Dependencies
Build: cmake ✘
Required: openssl ✔
==> Requirements
Required: macOS >= 10.10 ✔
==> Caveats
We've installed your MySQL database without a root password. To secure it run:
    mysql_secure_installation

MySQL is configured to only allow connections from localhost by default

To connect run:
    mysql -uroot

To have launchd start mysql now and restart at login:
  brew services start mysql
Or, if you don't want/need a background service you can just run:
  mysql.server start
==> Analytics
install: 67,118 (30 days), 215,596 (90 days), 887,578 (365 days)
install_on_request: 62,690 (30 days), 196,880 (90 days), 804,737 (365 days)
build_error: 0 (30 days)

brew uninstall mysql
Error: No such keg: /usr/local/Cellar/mysql

MacBook-Pro:~ jgonzalez$ brew link mysql@5.7 --force
Warning: Already linked: /usr/local/Cellar/mysql@5.7/5.7.25
To relink: brew unlink mysql@5.7 && brew link --force mysql@5.7

MacBook-Pro:~ jgonzalez$ brew unlink mysql 
Error: No such keg: /usr/local/Cellar/mysql

MacBook-Pro:~ jgonzalez$ brew switch mysql 5.7
Error: mysql not found in the Cellar.

MacBook-Pro:~ jgonzalez$ brew reinstall mysql@5.7
==> Reinstalling mysql@5.7 
==> Downloading https://homebrew.bintray.com/bottles/mysql@5.7-5.7.25.mojave.bottle.tar.gz
Already downloaded: /Users/jgonzalez/Library/Caches/Homebrew/downloads/9bea6ff9f2b392ad4d37e94a64969cc32fa3d373f0798c6400eb42e167bd2d4c--mysql@5.7-5.7.25.mojave.bottle.tar.gz
==> Pouring mysql@5.7-5.7.25.mojave.bottle.tar.gz
==> Caveats
We've installed your MySQL database without a root password. To secure it run:
    mysql_secure_installation

MySQL is configured to only allow connections from localhost by default

To connect run:
    mysql -uroot

mysql@5.7 is keg-only, which means it was not symlinked into /usr/local,
because this is an alternate version of another formula.

If you need to have mysql@5.7 first in your PATH run:
  echo 'export PATH="/usr/local/opt/mysql@5.7/bin:$PATH"' >> ~/.bash_profile

For compilers to find mysql@5.7 you may need to set:
  export LDFLAGS="-L/usr/local/opt/mysql@5.7/lib"
  export CPPFLAGS="-I/usr/local/opt/mysql@5.7/include"

To have launchd start mysql@5.7 now and restart at login:
  brew services start mysql@5.7
Or, if you don't want/need a background service you can just run:
  /usr/local/opt/mysql@5.7/bin/mysql.server start
==> Summary
🍺  /usr/local/Cellar/mysql@5.7/5.7.25: 319 files, 234MB

mysql -V
mysql  Ver 14.14 Distrib 5.7.25, for osx10.14 (x86_64) using  EditLine wrapper

MacBook-Pro:~ jgonzalez$ brew services restart mysql
Stopping `mysql`... (might take a while)
==> Successfully stopped `mysql` (label: homebrew.mxcl.mysql)
Error: Formula `mysql` is not installed.

**Comment by brendanfalkowski** [comment]
For reference, I had to forcefully remove all traces of MySQL and reinstall with Valet Plus to get it working again. I documented the issue and processes here:

- https://manuals.gravitydept.com/develop/environment-setup/valet-plus
- https://manuals.gravitydept.com/develop/command-line/brew

**Comment by sdouma** [comment]
I had this issue and saw another mysqld instance running. You can either remove that instance or just shutdown in settings preference > mac instead of removing all traces.
