### ISSUE TITLE
DNS issues after Composer global update

### ISSUE THREAD

**Issue by ladetryne** [weprovide/valet-plus#252]
Yesterday I ran a Composer global update && valet install && valet domain local && valet domain test

The reason for this was with an issue I had with a new magento2 install where it said no driver found or something like that when I tried to view the page and I found someone here with a similar issue that suggested that as a fix.

Now I have a problem where it seems nothing gets routed correctly. When I ping my .test domain it seems to work just fine. But if I try to open any of my pages in the browser I get nothing.

I have checked "valet paths" to make sure that the correct paths is still valid.

Any help to problem solve this would be very much appreciated! I am currently very lost here

**Comment by Neodork** [comment]
Dear Contributor,

With the release of Valet+ `2.0.0` the Valet+ development team and contributors have implemented the [contribution guidelines](https://github.com/weprovide/valet-plus/blob/master/CONTRIBUTING.md#issue-templates). The contribution guidelines aim to improve the support and workflow of Valet+. For further information why this was implemented please check https://github.com/weprovide/valet-plus/issues/393.

We're closing this ticket because it does not follow the correct format. If you feel your ticket is still relevant we encourage you to re-open your ticket using the [correct format](https://github.com/weprovide/valet-plus/issues/new/choose).

Kind regards,
The Valet+ team
