### ISSUE TITLE
FR: ability to switch PHP version per project.

### ISSUE THREAD

**Issue by SanderJP** [weprovide/valet-plus#26]
It would be amazing if we could switch php version per project directory. I have not set this up myself but a college of mine did: https://medium.com/@wvervuurt/how-to-run-multiple-php-versions-simultaneously-under-os-x-el-capitan-using-standard-apache-98351f4cec67
I'm not sure if this way is compatible with the way Valet+ is setup?

**Comment by timneutkens** [comment]
Since we don't have a need for this right now I'm going to leave this open as enhancement + help wanted 👌

**Comment by drbyte** [comment]
To do this would require at least:

For web:
- configure each version of PHP to have PHP-FPM bind to its own separate socket (different filename), instead of the generic default of `valet.sock`. 
- then configure the nginx config for the specific project to link to that specific socket for php-fpm
- (and prevent valet from damaging that override when it rewrites all configs in various commands such as `valet secure`

For command-line (ie: so `composer` and `artisan` work properly:
- update the PATH by inserting the specified PHP version's binary into the current terminal session. 
- This might require proxying PHP thru a valet call ... like `valet composer update` or `valet artisan migrate` etc.

And once all the config is prepped:
- then make sure the requested PHP version is both installed and started, via homebrew


Most of this can be done manually for each project. The most complicated part is setting separate sockets and updating "only" the specified project's nginx config.

**Comment by Neodork** [comment]
Dear Contributor,

With the release of Valet+ `2.0.0` the Valet+ development team and contributors have implemented the [contribution guidelines](https://github.com/weprovide/valet-plus/blob/master/CONTRIBUTING.md#issue-templates). The contribution guidelines aim to improve the support and workflow of Valet+. For further information why this was implemented please check https://github.com/weprovide/valet-plus/issues/393.

We're closing this ticket because it does not follow the correct format. If you feel your ticket is still relevant we encourage you to re-open your ticket using the [correct format](https://github.com/weprovide/valet-plus/issues/new/choose).

Kind regards,
The Valet+ team
