### ISSUE TITLE
Serve 404 image if images are broken?

### ISSUE THREAD

**Issue by pwhitehouse** [weprovide/valet-plus#265]
Is there a way to serve a specific 404 images if img src are broken?

I'm currently dev'ing a M2 site and the images are not pulled from the server on a make to save time.

**Comment by SanderAtom** [comment]
He, I've just hacked this together by copying the Magento2 driver from `~/.composer/vendor/weprovide/valet-plus/cli/drivers/Magento2ValetDriver.php` to the projectroot.
Then add this to the top of the `isStaticFile()` function:
```
if (strpos($uri, '/media/') === 0 &&
  pathinfo($sitePath . $uri)['extension'] == 'jpg') {
  return $sitePath . '/placeholder.jpg';
}
```
Then make sure the placeholder image is in the projectroot (not in /pub).
Of course add more extensions if needed.

**Comment by Neodork** [comment]
Dear Contributor,

With the release of Valet+ `2.0.0` the Valet+ development team and contributors have implemented the [contribution guidelines](https://github.com/weprovide/valet-plus/blob/master/CONTRIBUTING.md#issue-templates). The contribution guidelines aim to improve the support and workflow of Valet+. For further information why this was implemented please check https://github.com/weprovide/valet-plus/issues/393.

We're closing this ticket because it does not follow the correct format. If you feel your ticket is still relevant we encourage you to re-open your ticket using the [correct format](https://github.com/weprovide/valet-plus/issues/new/choose).

Kind regards,
The Valet+ team
