### ISSUE TITLE
Install - Setting password for root user failed

### ISSUE THREAD

**Issue by eclectic-coding** [weprovide/valet-plus#270]
After using Valet-plus for months on my MAC, it stopped working properly. I cannot connect to the MySQL database. I have been working to fix for the last few days but am now at a block. 

Valet install always finishes with: "Setting password for root user failed."

Any help would be appreciated. I have followed [246](https://github.com/weprovide/valet-plus/issues/246 ) but it has been no help. 

![screen shot 2018-12-04 at 1 04 30 pm](https://user-images.githubusercontent.com/13651291/49462908-3d11e100-f7c5-11e8-8f69-e6a8b2aed333.png)

**Comment by nickbasham** [comment]
Same for me – I've searched through every Github issue and Stack Overflow thread I could find, and followed all of them, including completely nuking my Valet+ install and reinstallation of everything, but still can't get MySQL 5.7 back up and running.

**Comment by polishedwp** [comment]
@nickbasham 
It seems mysql is not running:
worked through this [page](https://stackoverflow.com/questions/53616701/macos-mojave-brew-install-mysql5-7-access-denied-for-user-rootlocalhost)
mysql status indicates mysql not running, even though 
brew services list
indicates it is? Strange.

**Comment by nickbasham** [comment]
@polishedwp Yep, I got to the same conclusion. Somehow MySQL broke and now I'm just in a wild goose chase of errors trying to fix it – no combination of `brew uninstall`, `valet fix`, `brew doctor`, `valet install`, or other troubleshooting is helping.

**Comment by polishedwp** [comment]
I did just read an article from a few years ago suggesting using sql-5.6:
https://devmarketer.io/learn/do-not-install-mysql-macos-sierra-how-to-fix/ 

Interesting read, wonder if it works? 

For what its worth, I am having the same problem on Ubuntu/valet-linux in a Parrell virtual machine

**Comment by nickbasham** [comment]
Not sure what was different this time, but I just got it all back up and working.

Everything but MySQL was working, so I wiped it all again using this script: https://gist.github.com/dannygsmith/5b74ba708d7bf8621c1cb6b959ece99f/

After a reboot and `valet fix`, `valet install`, MySQL was the only service not working again. I added `/usr/local/opt/mysql@5.7/bin:$PATH` to my PATH and did `brew link --force mysql@5.7` to make sure mysql commands were going to the proper installation. I tried `mysql.server start` again, but it resulted in the familiar `ERROR! The server quit without updating PID file (/usr/local/var/mysql/BigBashMac.local.pid).` error.

I then tried `mysqld --initialize`, made note of the temporary password it created, then did `mysql.server start` again and MySQL finally started up! Once I reset the root password and reimported my database backups, I was back up and running.

**Comment by polishedwp** [comment]
Thanks, @nickbasham ... planning to try later. I have used Danny Smith's script but the other steps are new. Keep you posted.

**Comment by polishedwp** [comment]
I wasn't so fortunate.
![screen shot 2018-12-04 at 6 17 00 pm](https://user-images.githubusercontent.com/13651291/49479398-e9b58800-f7f0-11e8-95b4-ec99370d6257.png)

Looks like the first error is the problem. Where is the data directory initialize is looking at?

**Comment by nickbasham** [comment]
At least in my installation, that directory is `/usr/local/var/mysql`. I did a `rm -rf /usr/local/var/mysql` to delete the directory, which should let you go forward with the `--initialize` again.

**Comment by klocus** [comment]
I have the same error... I can't set password for root.

**Comment by philwinkle** [comment]
Same issue. Mysql mysteriously broke and no amount of troubleshooting / reinstall / reboot / permissions fix seems to work.

**Comment by samgranger** [comment]
Out of interest, did any of you update to Mojave prior to getting these issues? @klocus is your password empty? If so, try setting it once manually through cli.

**Comment by nickbasham** [comment]
@samgranger Nope, I'm actually still running Sierra, 10.12.6.

**Comment by polishedwp** [comment]
@samgranger most of us with these issues have had trouble resetting the password from the cli. It has been a frustrating experience. I did have better results using a `.my.cnf` file though. 
1. I eventually uninstalled valet-plus and myself.
2. Installed MySQL and somehow, was able to set a password. 
3. However, when I did a fresh install of `valet-plus`, it broke MySQL again. I was unable to fix. 
4. I tried MariaDB instead with `valet-plus` to no avail. 
5. Started over again ... 
6. Set up successfully MariaDB 
7. Installed `laravel/valet` successfully
8. Installed `aaemnnosttv/wp-cli-valet-command`

I am convinced this is a MySQL issue.

**Comment by klocus** [comment]
I tried set the password by CLI but I can't. I get error.

**Comment by klocus** [comment]
Any news?

**Comment by RGijsberts** [comment]
I'm having the same problem on a fresh install of OSX Mojave.

**Comment by nickbasham** [comment]
Just FYI, I finally upgraded to Mojave the other day, and my installation is still working. I'm not sure the mix of voodoo that got it working after doing the same thing failed in so many previous attempts (see https://github.com/weprovide/valet-plus/issues/270#issuecomment-444258461), but it's been stable so far and I just plan on not making any adjustments since I'm not sure how fragile it is.

**Comment by lfolco** [comment]
I was able to fix this issue by setting the path to Mysql in my `.bash_profile`:

`export PATH="/usr/local/opt/mysql@5.7/bin:$PATH"`

**Comment by LeeSaferite** [comment]
I think @lfolco has the right idea. I 'sovled' the issue by installing `myslq` first, then running `valet install`. I think the failure is that the mysql CLI is not on the path with the version valet is installing. By installing mysql manually or by adding the mysql@5.7 bin to the path you can then use the CLI client.

**Comment by Joshgallagher** [comment]
Had many issue installing Valet Plus on Mojave.

Ran into a DNSMasq and NGINX issue earlier and now this.

Found that the password for MySQL (root) is an empty string. So, to fix this I did:

`mysql.server restart`

And then:

`mysql_secure_installation`

This allowed me to reset the root password.

At this point, I can successfully use:

`valet db pwd <old> <new>`

To change my password back and forwards.

Also, as a note, you can access mysql like this `mysql` (as an anonymous user). Moreover, I was able to get into mysql like this: `mysql -uroot` and not specifying a password... Strange!

**Comment by ryanduff** [comment]
I had some old mysql data in the default location. Once I finally got connected I saw it, but I think the old root password was still there and thus blocking. Anyway, here's what I did to workaround since none of the usual stuff worked. 

`brew services stop mysql` (I think it's mysql, or maybe mysqld... I was using mariadb so just guessing here)
`mysql.server start --skip-grant-tables`
`mysql_secure_installation` ... enter for blank password, reset password to default of `root` and accepted all other defaults
`mysql.server stop`
`brew services start mysql` (or whatever it is. I used mariadb)

Then after this I was able to connect with `mysql -uroot -p` and entered `root` at the prompt. 

If that gets you clear you can use `valet db pwd <old> <new>` to set it to something other than the default.

**Comment by fnhipster** [comment]
Buenas! Buenas!

I had to deal with this issue while installing Valet+ on two different computers running macOS Mojave so I thought I'd share my recipe.

⚠️ **Make sure to back-up your database if you already have data in it.**

First, uninstall MySQL

`brew uninstall mysql`
`brew uninstall mysql@5.7`
`brew cleanup`
`rm -rf /usr/local/var/mysql`
`rm /usr/local/etc/my.cnf`

Now lets install MySQL 5.7

`brew install mysql@5.7`

You might have to link MySQL since 5.7 is not the latest version available in Homebrew (makes me wonder if this is the root of this issue)

`brew link --force mysql@5.7`

Run the service

`brew services start mysql@5.7`

Re-install Valet+

`valet fix`
`valet install`

**Comment by WinstonN** [comment]
@fridzema suggestion above worked - Thanks mate - Good one!

**Comment by itecedor** [comment]
Thank you @fnhipster!

**Comment by marcmanusch** [comment]
not woking for me at all... on two different macs

**Comment by brendanfalkowski** [comment]
For reference, I had to forcefully remove all traces of MySQL and reinstall with Valet Plus to get it working again. I documented the issue and processes here:

- https://manuals.gravitydept.com/develop/environment-setup/valet-plus
- https://manuals.gravitydept.com/develop/command-line/brew

**Comment by MikeiLL** [comment]
@fnhipster 

> ⚠️ **Make sure to back-up your database if you already have data in it.**

How is that done if MySql isn't working?

**Comment by Neodork** [comment]
Dear Contributor,

With the release of Valet+ `2.0.0` the Valet+ development team and contributors have implemented the [contribution guidelines](https://github.com/weprovide/valet-plus/blob/master/CONTRIBUTING.md#issue-templates). The contribution guidelines aim to improve the support and workflow of Valet+. For further information why this was implemented please check https://github.com/weprovide/valet-plus/issues/393.

We're closing this ticket because it does not follow the correct format. If you feel your ticket is still relevant we encourage you to re-open your ticket using the [correct format](https://github.com/weprovide/valet-plus/issues/new/choose).

Kind regards,
The Valet+ team

**Comment by andresams** [comment]
In my case what I did was to use `sudo mysql -u root` on the terminal. Then I changed the database to `mysql` and set up my password:

1. `use mysql;`
2. `SET PASSWORD FOR 'root'@'localhost' = PASSWORD("ROOTPASS");`

Reinstalling and other stuff didn't work out for me.

**Comment by battcor** [comment]
I was able to set the root password by running `sudo mysql_secure_installation`

I encountered `Setting password for root user failed.` after running the `valet install` command.

```
$ valet install --with-mariadb
[php] Checking for errors within the php installation...
...
[nginx] Restarting
Setting password for root user failed.

Valet installed successfully!
```

To set the root password, I had to run `sudo mysql_secure_installation`

```
$ sudo mysql_secure_installation
...
Change the root password? [Y/n] Y
New password:
Re-enter new password:
Password updated successfully!
Reloading privilege tables..
 ... Success!
...
Reload privilege tables now? [Y/n] Y
 ... Success!

Cleaning up...

All done!  If you've completed all of the above steps, your MariaDB
installation should now be secure.

Thanks for using MariaDB!
```

**Comment by manugentoo** [comment]
> I was able to set the root password by running `sudo mysql_secure_installation`
> 
> I encountered `Setting password for root user failed.` after running the `valet install` command.
> 
> ```
> $ valet install --with-mariadb
> [php] Checking for errors within the php installation...
> ...
> [nginx] Restarting
> Setting password for root user failed.
> 
> Valet installed successfully!
> ```
> 
> To set the root password, I had to run `sudo mysql_secure_installation`
> 
> ```
> $ sudo mysql_secure_installation
> ...
> Change the root password? [Y/n] Y
> New password:
> Re-enter new password:
> Password updated successfully!
> Reloading privilege tables..
>  ... Success!
> ...
> Reload privilege tables now? [Y/n] Y
>  ... Success!
> 
> Cleaning up...
> 
> All done!  If you've completed all of the above steps, your MariaDB
> installation should now be secure.
> 
> Thanks for using MariaDB!
> ```

saved my day!

**Comment by ptrollins** [comment]
After installing valet-plus from composer, you can update ``~/.composer/vendor/weprovide/valet-plus/cli/Valet/Mysql.php:setRootPassword`` and change `$this->cli->runAsUser(` to `$this->cli->runCommand(`. After doing this `valet install` installs with out set password error.

**Comment by MikeiLL** [comment]
> After installing valet-plus from composer, you can update `~/.composer/vendor/weprovide/valet-plus/cli/Valet/Mysql.php:setRootPassword` and change `$this->cli->runAsUser(` to `$this->cli->runCommand(`. After doing this `valet install` installs with out set password error.

Interesting. Would it make more sense if that was the native code, then?

**Comment by fpurser** [comment]
> After installing valet-plus from composer, you can update `~/.composer/vendor/weprovide/valet-plus/cli/Valet/Mysql.php:setRootPassword` and change `$this->cli->runAsUser(` to `$this->cli->runCommand(`. After doing this `valet install` installs with out set password error.

THANK YOUUUUUUUUUUUU i've been hunting everything down and so far this seems to be the only thing that worked for valet+ on Mojave
