### ISSUE TITLE
Any plans to add macports support?

### ISSUE THREAD

**Issue by freakpol** [weprovide/valet-plus#276]
May be this was answered before, but couldn't find any issue related to this.
DO you have plan to add support for macports (besides brew)?? (I mean, not replace one by another, but support both of them).

**Comment by Neodork** [comment]
Dear Contributor,

With the release of Valet+ `2.0.0` the Valet+ development team and contributors have implemented the [contribution guidelines](https://github.com/weprovide/valet-plus/blob/master/CONTRIBUTING.md#issue-templates). The contribution guidelines aim to improve the support and workflow of Valet+. For further information why this was implemented please check https://github.com/weprovide/valet-plus/issues/393.

We're closing this ticket because it does not follow the correct format. If you feel your ticket is still relevant we encourage you to re-open your ticket using the [correct format](https://github.com/weprovide/valet-plus/issues/new/choose).

Kind regards,
The Valet+ team
