### ISSUE TITLE
Documentation not clear about how to update from valet

### ISSUE THREAD

**Issue by wowcut** [weprovide/valet-plus#28]
The documentation gives no hint what I should do when I have already valet installed - is there an upgrade path? Should I remove valet?
This seems to be a very common situation: user found valet, then after some while, looking for more features, she finds valet+ so some words about how to upgrade / convert should address many people. 

BTW: very nice project! Thank you for your efforts!

**Comment by timneutkens** [comment]
We should definitely document this. I'll draft something 👌 

> BTW: very nice project! Thank you for your efforts!
Thanks 🤗

**Comment by lazyguru** [comment]
You might also consider adding a [replace](https://getcomposer.org/doc/04-schema.md#replace) block to your composer.json. Composer should then take care of removing laravel/valet when it installs Valet+

**Comment by timneutkens** [comment]
@lazyguru wow, nice!

**Comment by OgaBoss** [comment]
@timneutkens Please were you able to resolve this ? if yes and you say how. Thank you.

**Comment by lazyguru** [comment]
@OgaBoss you have to remove laravel/valet first.  Currently there is no "updating" to this package.

**Comment by Luminus** [comment]
@OgaBoss running `composer global remove laravel/valet` before running `valet install` took care of that for me.

For some reason, though, the tld was set to `.dev` and I had to run `sudo valet domain test` to get everything to play nice.

**Comment by Luminus** [comment]
Looks like I have version `1.0.3` for some reason even though I only just installed it. Running `composer global update` updated all my composer packages including bumping valet plus to `1.0.10`

**Comment by Neodork** [comment]
Dear Contributor,

With the release of Valet+ `2.0.0` the Valet+ development team and contributors have implemented the [contribution guidelines](https://github.com/weprovide/valet-plus/blob/master/CONTRIBUTING.md#issue-templates). The contribution guidelines aim to improve the support and workflow of Valet+. For further information why this was implemented please check https://github.com/weprovide/valet-plus/issues/393.

We're closing this ticket because it does not follow the correct format. If you feel your ticket is still relevant we encourage you to re-open your ticket using the [correct format](https://github.com/weprovide/valet-plus/issues/new/choose).

Kind regards,
The Valet+ team
