### ISSUE TITLE
Valet Plus Thinks I'm Root

### ISSUE THREAD

**Issue by leepeterson** [weprovide/valet-plus#281]
This issue has persisted for quite a while, and it's occurred while using a MacBook Pro running macOS 10.13, a MacBook Pro running macOS 10.14 and a MacBook Air running macOS 10.12.

dnsmasq will be configured to use a conf file in /var/root.

nginx tries to load configuration files from /var/root/.valet/Nginx/. nginx is also set with `fastcgi_pass unix:/var/root/.valet/valet.sock`.

I don't understand the need to run anything as root except for dnsmasq. nginx will run fine without sudo. Same with php; it runs fine without sudo.

When the installation process kicks off, it starts by asking for sudo, tries to determine the current user's home directories, then begins sticking things in the root user's home directory instead of my own.

The directory `~/.valet` is never created, either.

Yet, each and every time I run `valet install`, even though many of the core requirements needed to run valet properly weren't installed correctly, the resulting service list is:

```
dnsmasq    error   root /Library/LaunchDaemons/homebrew.mxcl.dnsmasq.plist
mailhog    started user  /Users/user/Library/LaunchAgents/homebrew.mxcl.mailhog.plist
mariadb    started user  /Users/user/Library/LaunchAgents/homebrew.mxcl.mariadb.plist
nginx      (started with issues) root /Library/LaunchDaemons/homebrew.mxcl.nginx-full.plist
php        stopped
php@7.1    (started with issues) root /Library/LaunchDaemons/homebrew.mxcl.php@7.1.plist
php@7.2    stopped
redis      started user  /Users/user/Library/LaunchAgents/homebrew.mxcl.redis.plist
```

... and the same message is always printed: 

```
Valet installed successfully!
```

I've manually fixed all of the issues, and I have to do so every time. I just don't understand the need to kick off everything using sudo when it's not required.

Just as the requirements state I should first install homebrew, php and composer, why not add dnsmasq to that list, then drop the sudo from the entire codebase? It seems to cause so many issues that it becomes a major deterrent.

**Comment by diazwatson** [comment]
@leepeterson what do you do to fix it manually?
I am having the same issue and tried moving everything from `/var/root/.valet/` to `~/.valet/` but that does not seems to fix the issue

**Comment by samgranger** [comment]
Interesting, will look into this issue.

**Comment by diazwatson** [comment]
I ended creating a symlink from `/var/root/.valet/` to `~/.valet/`.
Now everything works fine

**Comment by leepeterson** [comment]
I’ve stopped relying on Homebrew’s “services” feature. It isn’t very flexible and depends on socket and pid files to be placed in specific locations that it determines. Otherwise it displays “error” even if the config is valid and working. 

For instance, within my.conf, specify that MariaDB’s socket file be moved from /tmp/mysql.sock to /usr/local/run/mysql.sock and `brew services list` displays `error` for its status. 

Same with Nginx and php-fpm. 

This isn’t an issue on behalf of Valet, of course, but debugging any issue is then subject to doubt. It’s quite frustrating and maddening. 

In the end, my solution was simple: don’t depend on any config tools and build my own local dev stack. macOS already provides everything needed, and Caddyserver is working much better for me than Nginx.

**Comment by diazwatson** [comment]
I used to have my local dev stack configured directly in MacOS like you described and it was perfectly working.

Even so I decided to give Valet a try and I have to admit it saves me time. Plus I get some extra features I didn't have before (yes, because I did not spend time learning how to make them work).

It was not as easy and not as straight forward as I was expecting, but once you manage to fix some of the issues and therefore get familiar (I guess it is the same for everything else) to how things works it is great.

**Comment by leepeterson** [comment]
100% agree! And Valet has served me very well on many occasions the past couple years. 

Like I said, though, I see this being a problem with some of the tooling, and not Valet itself. I mean, we all run into bugs and need tools that give us accurate info. So when Homebrew reports back incorrect status info, ya kinda begin to lose trust in the tooling. 

Nevertheless, I’m sure I’ll check back 6 months or a year from now to see how things have evolved, and I’ll likely give it another shot.

**Comment by paul-gene** [comment]
I'm having this same issue.

I stopped the root services, and restarted normally, so all services are now running as my user. But this breaks everything and nothing works now.

**Comment by Neodork** [comment]
Dear Contributor,

With the release of Valet+ `2.0.0` the Valet+ development team and contributors have implemented the [contribution guidelines](https://github.com/weprovide/valet-plus/blob/master/CONTRIBUTING.md#issue-templates). The contribution guidelines aim to improve the support and workflow of Valet+. For further information why this was implemented please check https://github.com/weprovide/valet-plus/issues/393.

We're closing this ticket because it does not follow the correct format. If you feel your ticket is still relevant we encourage you to re-open your ticket using the [correct format](https://github.com/weprovide/valet-plus/issues/new/choose).

Kind regards,
The Valet+ team
