### ISSUE TITLE
Valet share for ssl

### ISSUE THREAD

**Issue by ghost** [weprovide/valet-plus#288]
Hi, is there any workaround to view ssl secured valet urls on a local network? Valet share won't work as stated in the docs.

**Comment by mischabraam** [comment]
`valet share` uses ngrok free version/plan to create the tunnel. The free plan doesn't support tunnelling for TLS, see https://ngrok.com/pricing.
You can purchase ngrok pro or business and set up the credentials according https://ngrok.com/docs#default-config-location

**Comment by mischabraam** [comment]
`valet share` however should use another command to tunnel secured URL's. So we will change this in valet.

**Comment by mischabraam** [comment]
Found a solution, you don't have to buy ngrok. It requires a change in the nginx configuration to work. I'll create a PR for it.

**Comment by Yackbz** [comment]
That's awesome. Thanks a lot.

A simple test.html file is working on ngrok.

Our setup is a little tricky as we have to use a certain url to access the project. The appliaction will always redirect to a fixed url.

Can I also use localhost or my network ip on other clients on the network to access the project without ngrok?
A neccessary url is something like this. 192.168.3.45/project_name.

Can I change that as well?

**Comment by Neodork** [comment]
Dear Contributor,

With the release of Valet+ `2.0.0` the Valet+ development team and contributors have implemented the [contribution guidelines](https://github.com/weprovide/valet-plus/blob/master/CONTRIBUTING.md#issue-templates). The contribution guidelines aim to improve the support and workflow of Valet+. For further information why this was implemented please check https://github.com/weprovide/valet-plus/issues/393.

We're closing this ticket because it does not follow the correct format. If you feel your ticket is still relevant we encourage you to re-open your ticket using the [correct format](https://github.com/weprovide/valet-plus/issues/new/choose).

Kind regards,
The Valet+ team
