### ISSUE TITLE
How to set up multiple Magento (1) sites in subfolders on same domain?

### ISSUE THREAD

**Issue by matt-bailey** [weprovide/valet-plus#300]
[A similar question has been asked before](https://github.com/weprovide/valet-plus/issues/77), but it doesn't seem to quite address what I'm looking for.

I have one Magento 1 installation that is serving up multiple sites on the same domain, but from subfolders. I'm struggling to get this working with valet/valet-plus. Basically I can get it working with subdomains, but not subfolders.

For example, I would like this:
- `mydomain.com/site1`
- `mydomain.com/site2`
- `mydomain.com/site3`
- etc...

Is this something I can configure in valet (using a `.env.valet` file), or is it more of a Magento config thing, or a combination of both? Can anyone help point me in the right direction?

**Comment by kalinstanchev** [comment]
Did you try the LocalValetDriver config? 
![image](https://user-images.githubusercontent.com/40825982/51323528-bfe6b680-1a68-11e9-9889-df9949f0c5dc.png)

**Comment by matt-bailey** [comment]
Thanks for the reply @kalinstanchev, I'll look into it. Do you know if this will work with sites in subfolders rather than subdomains though (I can get subdomains working, but not multi-sites in subfolders), e.g.?

```
mydomain.com/site1
mydomain.com/site2
mydomain.com/site3
```

**Comment by kalinstanchev** [comment]
Actually never tried it but maybe you can concatenate $_SERVER['HTTP_HOST'] with $_SERVER['REQUEST_URI'], I don't know 😟 
![image](https://user-images.githubusercontent.com/40825982/51327914-9468c980-1a72-11e9-9b92-467bb5e70c07.png)

**Comment by kalinstanchev** [comment]
Hello @matt-bailey,

Did you managed to achieve this?

**Comment by matt-bailey** [comment]
@kalinstanchev I've not had time to look into it yet, sorry. If I figure it out I'll update this ticket.

**Comment by jcdennen** [comment]
Any updates @matt-bailey ?

**Comment by just-tom** [comment]
@matt-bailey Also would like to know if you got websites working as sub folders? Thanks

**Comment by Neodork** [comment]
Dear Contributor,

With the release of Valet+ `2.0.0` the Valet+ development team and contributors have implemented the [contribution guidelines](https://github.com/weprovide/valet-plus/blob/master/CONTRIBUTING.md#issue-templates). The contribution guidelines aim to improve the support and workflow of Valet+. For further information why this was implemented please check https://github.com/weprovide/valet-plus/issues/393.

We're closing this ticket because it does not follow the correct format. If you feel your ticket is still relevant we encourage you to re-open your ticket using the [correct format](https://github.com/weprovide/valet-plus/issues/new/choose).

Kind regards,
The Valet+ team
