### ISSUE TITLE
Unable to create debug.log within WordPress

### ISSUE THREAD

**Issue by kupoback** [weprovide/valet-plus#301]
Using the latest version of valet-plus and declaring the proper defines within the `wp-config.php` of a WordPress project, I am unable to get the site, when it errors, to produce a debug.log which usually exists with the `themes` folder.

Now, while I can access the `php.log` within valet's folder, through workflow, its generally easier to look at the log for the project.

Is there something I'm missing or something that was disabled? I know there's xdebug packaged with this, however, it's a tool that is more than I need for my projects at the moment.

**Comment by ragulka** [comment]
I'm having the exact same issue. It looks like when WordPress tries to set the error log file location in https://github.com/WordPress/WordPress/blob/master/wp-includes/load.php#L347 - it just has no effect, and PHP is still using the valet error log path, ie `/Users/username/.valet/Log/php.log`

**Comment by Neodork** [comment]
Dear Contributor,

With the release of Valet+ `2.0.0` the Valet+ development team and contributors have implemented the [contribution guidelines](https://github.com/weprovide/valet-plus/blob/master/CONTRIBUTING.md#issue-templates). The contribution guidelines aim to improve the support and workflow of Valet+. For further information why this was implemented please check https://github.com/weprovide/valet-plus/issues/393.

We're closing this ticket because it does not follow the correct format. If you feel your ticket is still relevant we encourage you to re-open your ticket using the [correct format](https://github.com/weprovide/valet-plus/issues/new/choose).

Kind regards,
The Valet+ team
