### ISSUE TITLE
IMAP PHP Extension

### ISSUE THREAD

**Issue by helmerdavila** [weprovide/valet-plus#317]
I was trying to setup some Envato PHP Scripts, and it requires PHP IMAP extension, but it doesn't look active. 

Do you know if there is a way to activate this extension?

**Comment by Neodork** [comment]
Dear Contributor,

With the release of Valet+ `2.0.0` the Valet+ development team and contributors have implemented the [contribution guidelines](https://github.com/weprovide/valet-plus/blob/master/CONTRIBUTING.md#issue-templates). The contribution guidelines aim to improve the support and workflow of Valet+. For further information why this was implemented please check https://github.com/weprovide/valet-plus/issues/393.

We're closing this ticket because it does not follow the correct format. If you feel your ticket is still relevant we encourage you to re-open your ticket using the [correct format](https://github.com/weprovide/valet-plus/issues/new/choose).

Kind regards,
The Valet+ team

**Comment by iboved** [comment]
@helmerdavila did you found how to install/configure PHP IMAP extension in Laravel Valet?
