### ISSUE TITLE
Support Percona Server

### ISSUE THREAD

**Issue by robrecord** [weprovide/valet-plus#327]
Please could you add percona-server as an alternative to mariadb and mysql@5.7 - it's closer to mysql and thus a viable option.

**Comment by Neodork** [comment]
@robrecord Does it have brew support?

**Comment by samgranger** [comment]
Looks like it @Neodork - I agree @robrecord that this would be a nice addition.

**Comment by diazwatson** [comment]
```
brew install percona-server
```

**Comment by Neodork** [comment]
Dear Contributor,

With the release of Valet+ `2.0.0` the Valet+ development team and contributors have implemented the [contribution guidelines](https://github.com/weprovide/valet-plus/blob/master/CONTRIBUTING.md#issue-templates). The contribution guidelines aim to improve the support and workflow of Valet+. For further information why this was implemented please check https://github.com/weprovide/valet-plus/issues/393.

We're closing this ticket because it does not follow the correct format. If you feel your ticket is still relevant we encourage you to re-open your ticket using the [correct format](https://github.com/weprovide/valet-plus/issues/new/choose).

Kind regards,
The Valet+ team
