### ISSUE TITLE
Will Not Use Linked PHP Version

### ISSUE THREAD

**Issue by amcguireweb** [weprovide/valet-plus#328]
Hello, I seem to be unable to use the version of PHP that Valet Plus claims it is using again.

If I do `valet use 7.2` and `php -v`, I get:

![image](https://user-images.githubusercontent.com/8235324/53655155-723f9b00-3c1d-11e9-81d0-100a869da1bf.png)

However `phpinfo()` shows different:

![image](https://user-images.githubusercontent.com/8235324/53655050-3278b380-3c1d-11e9-9133-2c84b3c26c97.png)

Why isn't the version that I have linked and said to use isn't being used? I have tried restarting Valet Plus, Terminal, and my MacBook. Thanks for your help.

Valet+ 1.0.26
MacOS Mojave 10.14.3 (18D109)

**Comment by amcguireweb** [comment]
I was able to finally get the server to use PHP 7.2.13, but I'm not sure how. I believe that I followed these steps:

`brew unlink valet-php@7.1 --force`
`brew link valet-php@7.2`
Received warning that 7.2 was already linked, and to run the following to unlink and force relink:
`brew unlink valet-php@7.2 && brew link --force valet-php@7.2`
`valet use 7.2`
`valet restart`
I then closed out Terminal, shut down my MacBook, then turned on my MacBook. `phpinfo();` then showed 7.2.13.

Is this expected behavior? Should `valet restart` switch the PHP version and be ready for use at that time or is a `Terminal` and `machine` restart required?

Thank you for any clarification you may be able to provide.

**Comment by rosstafarian** [comment]
I have seen this before. Especially when switching between PHP versions. Nginx seems to want to hold on to versions. Removing `~/.valet/valet.sock` worked for me.

**Comment by amcguireweb** [comment]
This morning when I started my Mac the PHP version was randomly on 5.6 (with output from `phpinfo()`, when I last shut it down it was running php 7.2.

Now I can't get it to switch at all.

**Comment by rvdbogerd** [comment]
Make sure you run `brew doctor` when running into problems like these. In my case, homebrew could not link my php version to /usr/local/sbin, because the directory did not exist.

**Comment by MaxSouza** [comment]
In my case, I stop all services of php and start a specific version

**Comment by amcguireweb** [comment]
It doesn't matter what I do. I just can't switch back and forth. Instead, I spend an hour or two trying everything and then suddenly it switches for me. Currently in the middle of that process, once again.

**Comment by theozzz** [comment]
Hi all,

When u are suffering with this problem, just do:

- valet stop
- rm ~/.valet/valet.sock
- valet start

And everything will work again (thanks @rosstafarian)

**Comment by complexthings** [comment]
Could be you've added exports to `.zshrc` or `.bashrc` files to point to specific versions of php.

**Comment by SanderAtom** [comment]
@amcguireweb are you still having problems? You could join the Valet+ Slack channel (see the bottom of the readme of this project) so we can more easily debug what's going on.
In general if your terminal shows a different version than `phpinfo()` it's because there is something causing trouble in your `$PATH` variable. You can check this with `echo $PATH` in your terminal. `/usr/local/bin` should be somewhere at the start. If there is a specific php version in your `$PATH`, look for `export` lines in `~/.bash_profile` or `~/.bashrc` files and remove them.

**Comment by Neodork** [comment]
Dear Contributor,

With the release of Valet+ `2.0.0` the Valet+ development team and contributors have implemented the [contribution guidelines](https://github.com/weprovide/valet-plus/blob/master/CONTRIBUTING.md#issue-templates). The contribution guidelines aim to improve the support and workflow of Valet+. For further information why this was implemented please check https://github.com/weprovide/valet-plus/issues/393.

We're closing this ticket because it does not follow the correct format. If you feel your ticket is still relevant we encourage you to re-open your ticket using the [correct format](https://github.com/weprovide/valet-plus/issues/new/choose).

Kind regards,
The Valet+ team
