### ISSUE TITLE
valet use 7.x resets php.ini

### ISSUE THREAD

**Issue by gndk** [weprovide/valet-plus#329]
Using "valet use 7.x" resets the /usr/local/etc/valet-php/7.x/conf.d/z-performance.ini to default values.

For example resetting the memory_limit to 2G which I set to -1 because of composer.

Is it possible to set a default value here so this doesn't reset when changing php versions? If yes, where/how?

**Comment by SanderAtom** [comment]
You can work around this by adding your own file in `/usr/local/etc/valet-php/7.x/conf.d/`, make sure you call it something like `zz-local.ini` so it's loaded after `z-performance.ini` to overwrite those settings.

**Comment by Neodork** [comment]
Dear Contributor,

With the release of Valet+ `2.0.0` the Valet+ development team and contributors have implemented the [contribution guidelines](https://github.com/weprovide/valet-plus/blob/master/CONTRIBUTING.md#issue-templates). The contribution guidelines aim to improve the support and workflow of Valet+. For further information why this was implemented please check https://github.com/weprovide/valet-plus/issues/393.

We're closing this ticket because it does not follow the correct format. If you feel your ticket is still relevant we encourage you to re-open your ticket using the [correct format](https://github.com/weprovide/valet-plus/issues/new/choose).

Kind regards,
The Valet+ team
