### ISSUE TITLE
Mailhog not found with custom domain

### ISSUE THREAD

**Issue by jelleroorda** [weprovide/valet-plus#336]
See also #115.

I use a custom domain: `valet domain foo`.

![dnsmasq-changes](https://user-images.githubusercontent.com/9193686/54986713-70b28a00-4fb3-11e9-8fe5-24da0e08c5d0.png)

This results in mailhog not being found.

![mailhog-not-found](https://user-images.githubusercontent.com/9193686/54986646-511b6180-4fb3-11e9-913d-85669d9106d1.png)

**Comment by Serializator** [comment]
`valet domain [domain]` doesn't seem to actually update the `/usr/local/etc/nginx/valet/mailhog.conf` and `/usr/local/etc/nginx/valet/elasticsearch.conf`.

As a quick solution, try running `valet install` after `valet domain [domain]`, it should work then.
I'll create a PR to rewrite the `mailhog.conf` and `elasticsearch.conf` when using `valet domain [domain]`.

**Comment by samgranger** [comment]
PR merged, this will be available in the next release.

**Comment by Neodork** [comment]
Dear Contributor,

With the release of Valet+ `2.0.0` the Valet+ development team and contributors have implemented the [contribution guidelines](https://github.com/weprovide/valet-plus/blob/master/CONTRIBUTING.md#issue-templates). The contribution guidelines aim to improve the support and workflow of Valet+. For further information why this was implemented please check https://github.com/weprovide/valet-plus/issues/393.

We're closing this ticket because it does not follow the correct format. If you feel your ticket is still relevant we encourage you to re-open your ticket using the [correct format](https://github.com/weprovide/valet-plus/issues/new/choose).

Kind regards,
The Valet+ team
