### ISSUE TITLE
Needs a new name

### ISSUE THREAD

**Issue by mattstauffer** [weprovide/valet-plus#34]
I'm not a part of the Valet project, but I care about people handling things well, so I'm going to say something.

This project should have a new and unique name. In my totally-un-asked-for opinion, Valet+ is not an appropriate name for something that's not run by the people who created the original Valet. It's akin to forking Laravel and naming it Laravel$$$, or forking Drupal and naming it Drupal*.

-- 

As an aside, I'd also suggest burying the fact that the core of this code is Valet--that this project is Valet, with some modifications--a wee bit less. That's a bit of a separate issue, but again goes to the healthy and respectful relationship to the originator of code you forked. 

:heart:

**Comment by timneutkens** [comment]
@mattstauffer thanks for your feedback. First of all, we're not meaning to hurt anyone's feelings in any way, the reason I picked the name cause we were already using valet, and I didn't want to break the command already known by our employees 👌.

I do understand you point, and I'm not against renaming the project at all. Any suggestions are welcome 👍 ❤️

**Comment by mattstauffer** [comment]
@timneutkens <3 sounds great! I doubt anyone's feelings are hurt--you'll have to ask them--but I know that a rename could go a long way to clear up potential confusion.

Naming's a pretty personal thing, so I don't know if you're going to get really quality names from other people. It sounds like you're willing to rename it (woop!), and what I don't want is to see this issue die with the explanation of "well, no one suggested anything good."

Would you be willing to agree to make the decision to rename it *even if* no one came in this thread with a really fantastic name?

I'll do my best to brainstorm some good ones :) But no promises.

Additionally: thanks for listening. It's a joy to have potentially controversial interactions in a positive way.

**Comment by joshredwards** [comment]
Possible name you could use: Chauffeur. Although the spelling could be a problem.

Squire is short and sweet though!

**Comment by timneutkens** [comment]
I like Squire too! The only thing we need to keep in mind is that 1.0 was just released. Everyone just installed valet-plus using composer, and are using the `valet` command. So we'll have to figure out a graceful way to get the newly named package out to everyone. This comment might help with that: https://github.com/weprovide/valet-plus/issues/28#issuecomment-321612081

Then we should keep the `valet` command (to be backwards compatible) and add `squire` as a new command which both work the same way, then, after some time, we can remove `valet` altogether. Seems reasonable to me 😄

> Additionally: thanks for listening. It's a joy to have potentially controversial interactions in a positive way.

I'm always happy to discuss anything 👌

**Comment by jonphipps** [comment]
Just my $.02, but I think suggesting renaming in order to protect the Valet brand seems a bit draconian. I don't recall similar objections to [homestead_improved](https://github.com/Swader/homestead_improved). Perhaps this was because that project was extremely clear that it was an "upgraded fork of the original Laravel Homestead". 

That lack of clarity seems to be the main objection from both @adamwathan on Reddit: "the maintainers of the fork are taking a little too much credit in my opinion." and @mattstauffer's original 'aside', although personally I wouldn't put Valet in the same project class as Drupal or Doctrine.

This isn't an entirely different project, or even a different 'version' of Laravel Valet. It's a straightforward fork of Valet... plus some useful stuff, and in that sense valet-plus or Valet+ seems entirely reasonable. Perversely, it seems to me that merely changing the name makes this far less obvious and works _against_ the desire to more firmly credit the Valet creators and maintainers who provided the bulk of this project's code.

That said it _should_ be much more obvious that this is a fork of Valet. Unless you are _actually_ trying to take credit for Valet and the Valet approach to Mac development, why not follow the homestead_improved route and state in the project description that this is a fork of Valet plus some useful additions? It might also help to provide links to the official Laravel Valet documentation and note that you're providing a copy here as a matter of convenience.

And since it's not an official GitHub-flavour fork of Valet, personally I'd like some assurance that this disconnected project will be kept up-to-date with its Valet parent. Especially if you change the name in order to further isolate it from its origins.

**Comment by mattstauffer** [comment]
@jonphipps yah as I did the pull request I stared wondering if a much better readme, clearer fork relationship, and possibly just pulling in valet and then modifying it may actually be a *better* solution than a rename.

**Comment by mattstauffer** [comment]
(The last and should have been and/or; not sure how easy it would be to do since I don't know whether valet+ modifies any core files)

**Comment by timneutkens** [comment]
@mattstauffer most changes involved changing core files 😃

@jonphipps 
> That said it should be much more obvious that this is a fork of Valet. Unless you are actually trying to take credit for Valet and the Valet approach to Mac development

I agree

> And since it's not an official GitHub-flavour fork of Valet, personally I'd like some assurance that this disconnected project will be kept up-to-date with its Valet parent. Especially if you change the name in order to further isolate it from its origins.

I'm keeping it up to date as much as possible, I'll add that to the readme.

--

I'm fine with either solution 😄 The easiest is to change the documentation of course. It'll keep backwards compatibility with the original valet package. Though a new name would clear up any confusion there might be 👍

**Comment by ekandreas** [comment]
No, don't change the name. I found this project because I love Valet as a devenv but miss the things u added. Valet+ is just great and Squire feels more like something at a specific hub-web-page.

**Comment by timneutkens** [comment]
@mattstauffer @jonphipps @ekandreas I've updated the introduction. What do you think? https://github.com/weprovide/valet-plus#introduction

**Comment by timneutkens** [comment]
Thanks to @mattstauffer this issue has been resolved in #43 👌 🙌
