### ISSUE TITLE
valet: command not found

### ISSUE THREAD

**Issue by perteraul** [weprovide/valet-plus#340]
After following all of the installation steps,`valet fix` returns `valet: command not found`.

**Comment by oliwerhelsen** [comment]
Try this one: `export PATH="/usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin:/Users/user/.composer/vendor/bin:$PATH”`

**Comment by shyim** [comment]
Valet Plus PHP Versions are using a older icu version. You could downgrade it.

Check the answer https://stackoverflow.com/a/54273234
Commit Hash for the right icu version is bc0c97952453ff6afc146aa3a706e9902aba4300

**Comment by alexvandervegt** [comment]
You can downgrade icu4c following this:

http://hanxue-it.blogspot.com/2018/08/macos-homebrew-installing-older-version-of-software.html

**Comment by Neodork** [comment]
Dear Contributor,

With the release of Valet+ `2.0.0` the Valet+ development team and contributors have implemented the [contribution guidelines](https://github.com/weprovide/valet-plus/blob/master/CONTRIBUTING.md#issue-templates). The contribution guidelines aim to improve the support and workflow of Valet+. For further information why this was implemented please check https://github.com/weprovide/valet-plus/issues/393.

We're closing this ticket because it does not follow the correct format. If you feel your ticket is still relevant we encourage you to re-open your ticket using the [correct format](https://github.com/weprovide/valet-plus/issues/new/choose).

Kind regards,
The Valet+ team
