### ISSUE TITLE
Cannot find n98-magerun during install

### ISSUE THREAD

**Issue by ChrisButterworth** [weprovide/valet-plus#354]
`homebrew\php` is now empty so this package is no longer available is there an option to prevent it from trying to install?

**Comment by samgranger** [comment]
You can remove it with brew untap but sounds like you need to upgrade Valet+ completely - what Valet+ version are you running on?

**Comment by ChrisButterworth** [comment]
This is during installation (that I tried less than 24 hours ago) - followed the instructions and couldn't fails when running `valet install` stating `n98-magerun` could not be found

**Comment by marcmanusch** [comment]
same here:

`Marcs-iMac:~ marc$ valet install
[nginx] Stopping
[mysql] Stopping
[redis] Stopping
[devtools] Installing
[devtools] wp-cli already installed
[n98-magerun] Installing
Error: homebrew/php was deprecated. This tap is now empty as all its formulae were migrated.
Error: No available formula with the name "n98-magerun" 
==> Searching for a previously deleted formula (in the last month)...
Error: No previously deleted formula found.
Error: No similarly named formulae found.
==> Searching taps on GitHub...
==> Searching for similarly named formulae...
==> Searching taps...
Error: No formulae found in taps.


In Brew.php line 117:
                                             
  Brew was unable to install [n98-magerun].  
                                             

install [--with-mariadb]

`

**Comment by SanderAtom** [comment]
@marcmanusch can you run `valet fix`, it should switch from `homebrew/php` to `henkrehorst/homebrew-php`

**Comment by Neodork** [comment]
Dear Contributor,

With the release of Valet+ `2.0.0` the Valet+ development team and contributors have implemented the [contribution guidelines](https://github.com/weprovide/valet-plus/blob/master/CONTRIBUTING.md#issue-templates). The contribution guidelines aim to improve the support and workflow of Valet+. For further information why this was implemented please check https://github.com/weprovide/valet-plus/issues/393.

We're closing this ticket because it does not follow the correct format. If you feel your ticket is still relevant we encourage you to re-open your ticket using the [correct format](https://github.com/weprovide/valet-plus/issues/new/choose).

Kind regards,
The Valet+ team
