### ISSUE TITLE
Newbie error 

### ISSUE THREAD

**Issue by philipdrury** [weprovide/valet-plus#356]
I created a stripped dump for the development environment how do I merge this with the live enviroment?

**Comment by SanderAtom** [comment]
Hi @philipdrury, I'm not entirely sure what you are asking but it doesn't seem to be related to Valet+ specifically. Can you explain more?

**Comment by Neodork** [comment]
Dear Contributor,

With the release of Valet+ `2.0.0` the Valet+ development team and contributors have implemented the [contribution guidelines](https://github.com/weprovide/valet-plus/blob/master/CONTRIBUTING.md#issue-templates). The contribution guidelines aim to improve the support and workflow of Valet+. For further information why this was implemented please check https://github.com/weprovide/valet-plus/issues/393.

We're closing this ticket because it does not follow the correct format. If you feel your ticket is still relevant we encourage you to re-open your ticket using the [correct format](https://github.com/weprovide/valet-plus/issues/new/choose).

Kind regards,
The Valet+ team
