### ISSUE TITLE
Trying to setup valet plus with mariadb   HELP PLS!

### ISSUE THREAD

**Issue by 297Hacker** [weprovide/valet-plus#358]
I'm trying to setup valet plus with mariadb but i'm getting this error:

PHP Warning:  mysqli::__construct(): (HY000/2002): Connection refused in /Users/admin/.composer/vendor/weprovide/valet-plus/cli/Valet/Mysql.php on line 284

Warning: mysqli::__construct(): (HY000/2002): Connection refused in /Users/admin/.composer/vendor/weprovide/valet-plus/cli/Valet/Mysql.php on line 284
Failed to connect to database
PHP Warning:  mysqli_real_escape_string(): Couldn't fetch mysqli in /Users/admin/.composer/vendor/weprovide/valet-plus/cli/Valet/Mysql.php on line 305

Warning: mysqli_real_escape_string(): Couldn't fetch mysqli in /Users/admin/.composer/vendor/weprovide/valet-plus/cli/Valet/Mysql.php on line 305
PHP Fatal error:  Uncaught Error: Call to a member function query() on boolean in /Users/admin/.composer/vendor/weprovide/valet-plus/cli/Valet/Mysql.php:264

(https://user-images.githubusercontent.com/7156032/58212373-d50d7380-7cee-11e9-990d-3c08e63f4656.jpg)

I already run  $valet install --with-mariadb
and $brew install mariadb
also run rm -rf /usr/local/var/mysql/*
to remove mysql completely

**Comment by SanderAtom** [comment]
If you still have problems with this, please join the Valet+ slack channel (see bottom of the readme), it's quicker to debug what's going on.

**Comment by 297Hacker** [comment]
yeah i'm still getting this problem. I think I fucked up my whole system. different version in different places installed. I will join the valet+ slack channel then.

**Comment by Neodork** [comment]
Dear Contributor,

With the release of Valet+ `2.0.0` the Valet+ development team and contributors have implemented the [contribution guidelines](https://github.com/weprovide/valet-plus/blob/master/CONTRIBUTING.md#issue-templates). The contribution guidelines aim to improve the support and workflow of Valet+. For further information why this was implemented please check https://github.com/weprovide/valet-plus/issues/393.

We're closing this ticket because it does not follow the correct format. If you feel your ticket is still relevant we encourage you to re-open your ticket using the [correct format](https://github.com/weprovide/valet-plus/issues/new/choose).

Kind regards,
The Valet+ team
