### ISSUE TITLE
Installation over Valet

### ISSUE THREAD

**Issue by bezner** [weprovide/valet-plus#360]
I'm using Valet but want to easy switch between php versions for legacy projects (people still use php 5.6!). Do I need to uninstall Valet prior installing Valet+ and how? It would benefit if your documentation covered that case. 

Thanks 

Arthur

**Comment by SanderAtom** [comment]
Hi @bezner yes it's recommended to completely remove Valet first, you might still run into old config files messing things up, but Valet+ has the command `valet fix` which tries to fix most errors in a setup.
You can join the Valet+ slack channel for help if you run into problems.

**Comment by mischabraam** [comment]
Maybe this will help to uninstall Laravel's Valet, https://stackoverflow.com/questions/40276967/uninstall-laravel-valet

**Comment by Neodork** [comment]
Dear Contributor,

With the release of Valet+ `2.0.0` the Valet+ development team and contributors have implemented the [contribution guidelines](https://github.com/weprovide/valet-plus/blob/master/CONTRIBUTING.md#issue-templates). The contribution guidelines aim to improve the support and workflow of Valet+. For further information why this was implemented please check https://github.com/weprovide/valet-plus/issues/393.

We're closing this ticket because it does not follow the correct format. If you feel your ticket is still relevant we encourage you to re-open your ticket using the [correct format](https://github.com/weprovide/valet-plus/issues/new/choose).

Kind regards,
The Valet+ team
