### ISSUE TITLE
A Command To Enable / Disable MySQL Service

### ISSUE THREAD

**Issue by austinkregel** [weprovide/valet-plus#361]
I was hoping there might be a way to toggle the MySQL server. Akin to how we can toggle redis, elasticsearch, varish, ect. 😄 

While I do normally use MySQL I use a specific docker container for it (the same one that matches my prod server). For some reason the MySQL server will hog the port and docker won't throw an error if the ports already taken (even tho it should) (I've been running into this more frequently, it's more annoying than anything).

If anyone has any better suggestions for my current problem, I'll be more than happy to give it a go!

**Comment by SanderAtom** [comment]
You can try `brew services stop mysql@5.7`, which will free up the port. We could add a simple command for that in valet yea.

**Comment by Neodork** [comment]
Dear Contributor,

With the release of Valet+ `2.0.0` the Valet+ development team and contributors have implemented the [contribution guidelines](https://github.com/weprovide/valet-plus/blob/master/CONTRIBUTING.md#issue-templates). The contribution guidelines aim to improve the support and workflow of Valet+. For further information why this was implemented please check https://github.com/weprovide/valet-plus/issues/393.

We're closing this ticket because it does not follow the correct format. If you feel your ticket is still relevant we encourage you to re-open your ticket using the [correct format](https://github.com/weprovide/valet-plus/issues/new/choose).

Kind regards,
The Valet+ team
