### ISSUE TITLE
Uncaught Error: Call to undefined function apcu_fetch()

### ISSUE THREAD

**Issue by nbedevi** [weprovide/valet-plus#381]
**This error appear when I request the domain**

Fatal error: Uncaught Error: Call to undefined function apcu_fetch() in /Users/nuruddin/.composer/vendor/weprovide/valet-plus/server.php:51 Stack trace: #0 {main} thrown in /Users/nuruddin/.composer/vendor/weprovide/valet-plus/server.php on line 51

`❯ brew services list`

![Screen Shot 2019-07-08 at 11 37 22 AM](https://user-images.githubusercontent.com/5736522/60796238-b74c7e80-a175-11e9-8bca-b0d1b70de313.png)

```
❯ php -v
PHP 7.2.20
```

```
❯ pecl list

Installed packages, channel pecl.php.net:
=========================================
Package Version State
apcu    5.1.17  stable
apcu_bc 1.0.5   stable
geoip   1.1.1   beta
yaml    2.0.4   stable
```

**Comment by fransyrcc** [comment]
@NuruddinBadawi could you check your `php.ini` file?
```
extension="apcu.so"
extension="geoip.so"
extension="apc.so"
...
[PHP]
```
Sometimes ` extension="apcu.so"` is duplicated. If there is duplication delete all extesions (all before [PHP]) and save the file. Then try to run `valet install`

 To know what `php.ini` you are  using run `php --ini` to see the location of it.
Hope it helps!

**Comment by labelworx** [comment]
I had this issue too doing a fresh install on Mojave.  Removing the duplicated line i php.ini worked for me.

> extension="apcu.so"

**Comment by maiorano84** [comment]
Problem appears to be related to #349, and it doesn't look like anybody plans on fixing it anytime soon.

**Comment by Neodork** [comment]
Dear Contributor,

With the release of Valet+ `2.0.0` the Valet+ development team and contributors have implemented the [contribution guidelines](https://github.com/weprovide/valet-plus/blob/master/CONTRIBUTING.md#issue-templates). The contribution guidelines aim to improve the support and workflow of Valet+. For further information why this was implemented please check https://github.com/weprovide/valet-plus/issues/393.

We're closing this ticket because it does not follow the correct format. If you feel your ticket is still relevant we encourage you to re-open your ticket using the [correct format](https://github.com/weprovide/valet-plus/issues/new/choose).

Kind regards,
The Valet+ team
