### ISSUE TITLE
innodb_file_per_table is OFF in my.cnf

### ISSUE THREAD

**Issue by timtox** [weprovide/valet-plus#386]
**Large file ibdata1 can not be shrunk**
This is mostly an MySQL related issue but still something that can be improved through configuration. 

**Problem**
In the default config file `~/.composer/vendor/weprovide/valet-plus/cli/stubs/my.cnf` is `innodb_file_per_table` set to `OFF`. As a user at stackoverflow stated, MySQL 5.6 enables `innodb_file_per_table` by default. But with the setting `OFF`, if you import large dumps often, the ibdata1 file grows large and can not be shrunk again. 

Read more about the ibdata1 file: https://stackoverflow.com/questions/3456159/how-to-shrink-purge-ibdata1-file-in-mysql

**Question**
I searched in the Github Issues and PRs but did not found anything related, therefore i opened this issue. Why is this config value explicit set to be disabled?

**Solution**
If appropriate, i would like to open a PR in which the config value is set to `ON`.

**Comment by WinstonN** [comment]
@timtox I hear you. I had the same issue, and after the last time of shrinking my ibdata file which was over 50GB, then dumping all my db's, and reimporting them I set this value to ON
```
innodb_file_per_table=ON
```
but I have bad news for you. I experienced a LOT of mysql crashes....so bad that I could not even install a default magento

In the end, I set that back to OFF, and the crashes are gone
```
innodb_file_per_table=OFF
```

**Comment by timtox** [comment]
@WinstonN Thank you for answering my question :) 

On my local machine i did not experienced MySQL crashes after changing the value to `ON`. I have Mac OS Mojave (10.14.6) and MySQL 5.7. From colleagues i heard that this MySQL version is a little bit buggy under Mac OS. Maybe that is the case.

I took the following steps for updating my local DB:

- `mysqldump` [all tables i want to keep]
- `DROP DATABASE` [database_name]
- `brew services stop mysql@5.7`
- `rm /usr/local/var/mysql/ibdata1`
- `rm /usr/local/var/mysql/ib_logfile*`
- `brew services start mysql@5.7`
- `create database` [database_name]

Then i imported the previously stored dumps back into the newly created databases.

**Comment by darthsteven** [comment]
I've had a single machine that did have issues with using the file per table option, and that was because we were actually hitting the inode limit of the machine (we had thousands of databases with thousands of tables, don't ask).
Otherwise, literally no problems.
Given that this is developer tool, I suggest that the killer feature here is that I can do a one-off import of a large DB, drop it and I'll actually be able to reclaim that disk space :)

**Comment by Neodork** [comment]
Dear Contributor,

With the release of Valet+ `2.0.0` the Valet+ development team and contributors have implemented the [contribution guidelines](https://github.com/weprovide/valet-plus/blob/master/CONTRIBUTING.md#issue-templates). The contribution guidelines aim to improve the support and workflow of Valet+. For further information why this was implemented please check https://github.com/weprovide/valet-plus/issues/393.

We're closing this ticket because it does not follow the correct format. If you feel your ticket is still relevant we encourage you to re-open your ticket using the [correct format](https://github.com/weprovide/valet-plus/issues/new/choose).

Kind regards,
The Valet+ team

**Comment by darthsteven** [comment]
@Neodork I'd love to reformat this issue into the proper format, can it be re-opened so I can re-format it please?

**Comment by Neodork** [comment]
@darthsteven Looks like you're not the owner of the ticket. Could you create a new one? We would like to have the format in the OP. If you do and tag me I'll review it and make sure we can pick it up.
