### ISSUE TITLE
Unable to switch PHP versions

### ISSUE THREAD

**Issue by jawittdesigns** [weprovide/valet-plus#388]
The only PHP version I can get working is 7.1. If I switch to 7.2 or7.3 I get a 502 Bad Gateway error

**Comment by timtox** [comment]
Did you tried a `valet restart` after switching the PHP version?

**Comment by jawittdesigns** [comment]
@timtox Oh, yeah. I tried everything I could think of. Nothing seems to work.

I'm not even convinced it was installed correctly. The installation is so completely broken (see  #318). 

I had to jump though so many hoops to get it installed. I tried documenting what I did, but it eventually became so convoluted that I couldn't keep track.

I initially installed it to get ionCube, and it dosn't even seem to work.

I've given up on Valet+ only after a weekend. This project is so broken.

**Comment by mischabraam** [comment]
Can you provide details/information about the problem/error you run into?

**Comment by jawittdesigns** [comment]
Well simply put, it's not switching PHP versions or there the install failed. With any PHP version besides 7.1 I get a 502 error.

You should really look here #318. 

It took me 6 hours just to get this installed. There's something seriously broken with Valet+.

**Comment by mischabraam** [comment]
I agree, ran into problems too. Others as well, see also https://github.com/weprovide/valet-plus/issues/391#issuecomment-522329656
I think also switching from Laravel's Valet to Valet+ is not an easy transfer, all kinds of version collisions and config files. However, you can't hold Valet+ responsible for not getting Laravel's Valet properly uninstalled. Then again, even on fresh install issues raise. The docs also are not complete.

Anyway, we've planned to work on these install issues shortly.

**Comment by pixelhed** [comment]
i also had this issue `valet use 7.whatever` simply was no longer working. After much reading of the solutions, and experimenting i finally found a reliable solution. I'm using zsh, but i think that these instructions should work for whichever shell you use:

1. unlink existing php version, for example PHP 7.1  `brew unlink valet-php@7.1`
2. link new version, for example PHP 7.2 `brew link --force valet-php@7.2`
3. edit `~/.zshrc` (or whichever file your shell uses) 
    `export PATH="/usr/local/opt/valet-php@7.2/bin:$PATH"`
    `export PATH="/usr/local/opt/valet-php@7.2/sbin:$PATH"`
4. reinstall valet `valet install`

If i follow this process it works each time.. Hope this helps someone

**Comment by utklasad** [comment]
@lfolco same problem here!

**Comment by Neodork** [comment]
Dear Contributor,

With the release of Valet+ `2.0.0` the Valet+ development team and contributors have implemented the [contribution guidelines](https://github.com/weprovide/valet-plus/blob/master/CONTRIBUTING.md#issue-templates). The contribution guidelines aim to improve the support and workflow of Valet+. For further information why this was implemented please check https://github.com/weprovide/valet-plus/issues/393.

We're closing this ticket because it does not follow the correct format. If you feel your ticket is still relevant we encourage you to re-open your ticket using the [correct format](https://github.com/weprovide/valet-plus/issues/new/choose).

Kind regards,
The Valet+ team
