### ISSUE TITLE
Bug: Craft 3 Driver for Multisite Setups

### ISSUE THREAD

**Issue by samhibberd** [weprovide/valet-plus#422]
Error when accessing sites via the subfolder method, it looks to have been fixed in the latest Craft Valet driver: 

https://github.com/laravel/valet/blob/master/cli/drivers/CraftValetDriver.php

**Comment by Neodork** [comment]
Dear Contributor,

With the release of Valet+ `2.0.0` the Valet+ development team and contributors have implemented the [contribution guidelines](https://github.com/weprovide/valet-plus/blob/master/CONTRIBUTING.md#issue-templates). The contribution guidelines aim to improve the support and workflow of Valet+. For further information why this was implemented please check https://github.com/weprovide/valet-plus/issues/393.

We're closing this ticket because it does not follow the correct format. If you feel your ticket is still relevant we encourage you to re-open your ticket using the [correct format](https://github.com/weprovide/valet-plus/issues/new/choose).

Kind regards,
The Valet+ team
