### ISSUE TITLE
phpredis support

### ISSUE THREAD

**Issue by royduin** [weprovide/valet-plus#432]
Laravel switched from predis to phpredis in 6.x, see the upgrade guide: https://laravel.com/docs/6.x/upgrade#redis-default-client, having this PHP extension by default when using Redis would be nice.

**Comment by Neodork** [comment]
We're currently not planning any such support without a PR. But you can easily manage this by doing `pecl install redis-<correct version for your PHP verion>`. Check versions here:

https://pecl.php.net/package/redis

**Comment by Neodork** [comment]
Dear Contributor,

With the release of Valet+ `2.0.0` the Valet+ development team and contributors have implemented the [contribution guidelines](https://github.com/weprovide/valet-plus/blob/master/CONTRIBUTING.md#issue-templates). The contribution guidelines aim to improve the support and workflow of Valet+. For further information why this was implemented please check https://github.com/weprovide/valet-plus/issues/393.

We're closing this ticket because it does not follow the correct format. If you feel your ticket is still relevant we encourage you to re-open your ticket using the [correct format](https://github.com/weprovide/valet-plus/issues/new/choose).

Kind regards,
The Valet+ team
