### ISSUE TITLE
Enhancement: Add PimpMyLog

### ISSUE THREAD

**Issue by dannygsmith** [weprovide/valet-plus#47]
It is trivial to add, but it would be nice if PimpMyLog was added by default.  http://pimpmylog.com/

**Comment by timneutkens** [comment]
Good idea, lets see if we can implement it :ok_hand:

**Comment by viktorbijlenga** [comment]
One simple way to add this manually would be.

1. Install Pimp My Log
`composer global require "potsky/pimp-my-log"`
2. Create a domain for it, using Valet Plus
`cd /Users/$USER/.composer/vendor/potsky/pimp-my-log && valet link`
3. Visit `pimp-my-log.test` in your browser and follow the step-by-step instructions.

**Comment by Neodork** [comment]
Dear Contributor,

With the release of Valet+ `2.0.0` the Valet+ development team and contributors have implemented the [contribution guidelines](https://github.com/weprovide/valet-plus/blob/master/CONTRIBUTING.md#issue-templates). The contribution guidelines aim to improve the support and workflow of Valet+. For further information why this was implemented please check https://github.com/weprovide/valet-plus/issues/393.

We're closing this ticket because it does not follow the correct format. If you feel your ticket is still relevant we encourage you to re-open your ticket using the [correct format](https://github.com/weprovide/valet-plus/issues/new/choose).

Kind regards,
The Valet+ team
