### ISSUE TITLE
Is valet+ dead?

### ISSUE THREAD

**Issue by zcuric** [weprovide/valet-plus#523]
Hi, really love this version of `valet`. Have been using it heavily. But there were not any commits since February of this year. 
So my question is what is the future of `valet+`? Is it dead or will you continue for maintain it? What is you plan? 

There are some forks that seem to be kind of active, like https://github.com/MarcoFaul/valetPlusReforged but they still really  on this repository. 

Thanks!

**Comment by Neodork** [comment]
Dear @zcuric,

Although I cannot speak for others. For me my free time took a hit due to changes brought by COVID-19. Which means I have less time to spend. Every now and then the company would provide some sponsored time in which I could do maintenance to prevent overheads. This has also taken a massive hit due to corporate restructuring.

That being said, we're still actively supporting Valet+. We're however not bringing out updates fast enough on the application side. There is however a contributor guide and if you adhere to that and provide a PR you can always tag some of the main contributors to ensure it gets merged. Although I feel like projects like https://github.com/MarcoFaul/valetPlusReforged are a great initiative. I feel like they should only be used to provide good PR's towards the main repository. Otherwise we're just dividing our community instead of unifying it.

That being said Valet+ is a lot more than just the application level. One of our contributors updated the entire automation for Valet+ PHP versions (Note: We still support PHP 5.6) not too long ago. And most main contributors still use Valet+ on a daily basis. 

So all that being said **Valet+ is definitely not dead**. The application side could use some more care and love, that's for sure.

I'll leave this thread open for a few weeks so some discussion can take place.

**Comment by zcuric** [comment]
Dear @Neodork

> Although I cannot speak for others. For me, my free time took a hit due to changes brought by COVID-19. Which means I have less time to spend. Every now and then the company would provide some sponsored time in which I could do maintenance to prevent overheads. This has also taken a massive hit due to corporate restructuring.

I'm sorry about that and I hope you all will recover and come out stronger than before!

> That being said, we're still actively supporting Valet+. We're however not bringing out updates fast enough on the application side. There is however a contributor guide and if you adhere to that and provide a PR you can always tag some of the main contributors to ensure it gets merged

These are great news! I'll  try to submit my first PR as soon as possible. My biggest issue is that Magento is in 2.4 and has breaking changes that Valet+ can't support right now. I hope that community around Valet+ will come together and contribute to make this awesome project more awesome. I hope that @MarcoFaul will contribute the changes he made to his fork to original repo. 

>  Although I feel like projects like https://github.com/MarcoFaul/valetPlusReforged are a great initiative. I feel like they should only be used to provide good PR's towards the main repository. Otherwise we're just dividing our community instead of unifying it.

Totally agree with you. 

> So all that being said Valet+ is definitely not dead. The application side could use some more care and love, that's for sure.

Let's hope for the best!

**Comment by zcuric** [comment]
@Neodork My first and simple contribution is here #524  :)

**Comment by Neodork** [comment]
Closing this as development has picked up and not more discussion is taking place.
