### ISSUE TITLE
Can I use default (brew) PHP formula instead of the custom valet-php?

### ISSUE THREAD

**Issue by valentinocossar** [weprovide/valet-plus#545]
Hi,

As reported in the [installation guide](https://github.com/weprovide/valet-plus/wiki/Installation), I have to install via `brew` the `valet-php@7.2` formula. It's a necessary step? Or I can stick with the default brew formula installed with `brew install php` (PHP 7.4).

Thank you.

**Comment by Neodork** [comment]
@valentinocossar You can start up a brew PHP version and use Valet+. HOWEVER any valet+ command that requires a valet-php version linked will not work. 

Any development within your framework without any specific valet commands will work just fine.

**Comment by valentinocossar** [comment]
Super! Thank you for your answer! For example which commands need a valet-php version?

**Comment by Neodork** [comment]
@valentinocossar Mostly the ones related to, or using the PHP-FPM class. So that would be stuff like: `valet install`, `valet stop`, `valet start`, `valet use`. 

If you manually switch back it will all work again though. Just ensure you're only running 1 kind of PHP when trying to run such Valet+ commands and your should be fine.

**Comment by valentinocossar** [comment]
@Neodork Thank you!
