### ISSUE TITLE
Elasticsearch version

### ISSUE THREAD

**Issue by yhoiseth** [weprovide/valet-plus#55]
`valet elasticsearch install` [installs Elasticsearch 2.4](https://github.com/weprovide/valet-plus/blob/11a0cfba84f96d7c4574d8ed423ad978ad4990d0/cli/Valet/Elasticsearch.php#L45).

I started digging into this because I have some issues with fielddata on `bin/console fos:elastica:populate`:

```
[Elastica\Exception\ResponseException]                                                                                                    
  fielddata should be a hash but was of type: class java.lang.Boolean [reason: Failed to parse mapping [text]: fielddata should be a hash   
  but was of type: class java.lang.Boolean]   
```

This used to work when I had simply run `brew install elasticsearch && brew services start elasticsearch`. To be clear, I'm not 100 % sure about this, as I haven't troubleshooted it for fear of messing up my brand new Valet Plus (and macOS) install.

`brew info elasticsearch` gives the following result:

```
elasticsearch: stable 5.5.2, HEAD
…
```

I have two questions:
1. Why does Valet Plus use Elasticsearch 2.4?
3. Is there a way to undo `valet elasticsearch install`?

**Comment by timneutkens** [comment]
1. It's cause it's a requirement of Magento 2
2. `brew uninstall elasticsearch@2.4` doesn't harm anything 👌 Then you can install elastic version 5 using `brew install elasticsearch`

**Comment by timneutkens** [comment]
I guess we should allow installing v5 and provide an explanation in the docs as to why we install 2.4

**Comment by OZZlE** [comment]
The site I am working on uses M1 and ES V.6, and the installation of 2.4 has just caused a lot of issues and headaches for me because my computer randomly switched to using 2.4 rather than V.6 which I also installed.. 

I am thinking `valet-plus` isn't only made for Magento development? So it's a bit strange to install such an old version of ES by default. I think it should be optional like `valet install --optimize-for-magento2` or `valet install --with-elasticsearch --elasticsearch-v2` or something similar
