### ISSUE TITLE
Valet plus constraint not allowing me to install Laravel/Envoy

### ISSUE THREAD

**Issue by CrixuAMG** [weprovide/valet-plus#552]
I cannot install laravel/envoy on my macbook due to this package's version constraints on symphony/process...

```
 ~ composer global require laravel/envoy -W
Changed current directory to /Users/christian/.composer
Using version ^2.4 for laravel/envoy
./composer.json has been updated
Running composer update laravel/envoy --with-all-dependencies
Loading composer repositories with package information
Updating dependencies
Your requirements could not be resolved to an installable set of packages.

  Problem 1
    - weprovide/valet-plus is locked to version 2.1.0 and an update of this package was not requested.
    - weprovide/valet-plus 2.1.0 requires symfony/process ~2.7|~3.0 -> found symfony/process[v2.7.0, ..., v2.8.52, v3.0.0, ..., v3.4.47] but it conflicts with another require.

Use the option --with-all-dependencies (-W) to allow upgrades, downgrades and removals for packages currently locked to specific versions.
``` 

Is there a reason this package requires this specific version  of symfony/process or could it be updated/loosened up a bit?

**Comment by jemoon** [comment]
@CrixuAMG 
Once You will need to have multiple composer packages installed globally but some of them will lock specific dependency You may encounter an issue which wont allow You to install desired package - it is a known issue because composer handles global composer.lock config placed in ~/.composer/composer.lock In order to solve this issue You should install and use https://packagist.org/packages/consolidation/cgr - all informations about they way it should be installed and used are well documented on theirs site.
