### ISSUE TITLE
Bug: macOS Ventura 13.1 Background Items Spam

### ISSUE THREAD

**Issue by JoshuaLuckers** [weprovide/valet-plus#617]
- [x] I've checked the issue queue and could not find anything similar to my bug.
- [x] I'm on the latest version of valet-plus (`valet --version`): `2.4.0-beta6`
- [x] I've run `valet fix` and `valet install` after updating and before submitting my issue/feature.

**What is the problem?**
After upgrading to macOS Ventura 13.1 I get spammed by "Background Items Added" notifications.
<img width="370" alt="Screenshot 2022-12-22 at 09 03 31" src="https://user-images.githubusercontent.com/1268085/209087319-3a62883f-e454-4dc1-bb89-0aed886562c1.png">

**What was supposed to happen?**
No "Background Items Added" notification should show.

**What actually happened?**
After a reboot/boot I get spammed by "Background Items Added" notifications. Mostly about MailHog.
Restarting Valet+ usually solves this, until I reboot again.

**How to reproduce this?**
Install Valet+ on macOS Ventura 13.1. Reboot/boot your computer.

**What is the solution?**
No idea!

**Comment by anotherjames** [comment]
I experience this too, plus my mailhog service has failed to actually start. It feels as though it keeps trying, and that's why the notifications keep appearing?

**Comment by anotherjames** [comment]
For me, running `valet install` does then make mailhog work, and further notifications about mailhog then stop. But the many many existing notifications are still on the screen, and I had to enter my system password maybe 30 times to allow the 'System Certificate Trust Settings' to be updated. I have to do this after every time I boot up my mac ... that's not going to fly!

**Comment by JoshuaLuckers** [comment]
@anotherjames yeah same here, `valet restart` usually also fixes the notification spam. After a reboot the notification spam starts again.

I don't think this is necessarily a bug with Valet+ but with macOS (let's hope a future release of Ventura addresses it).

**Comment by anotherjames** [comment]
I have found some sort of progress - via https://www.reddit.com/r/MacOSBeta/comments/yecvhm/comment/j0h8roz/?utm_source=reddit&utm_medium=web2x&context=3 - the repeated notifications are due to a code signing issue, so following the steps there meant I could sign the Mailhog app, though I also had to with `sudo`, which may or may not be appropriate for everyone.

For me, it came down to running: `codesign -f -s - /usr/local/opt/mailhog/bin/MailHog` ... and then trying again with `sudo` because I got a "internal error in Code Signing subsystem" error back initially. The path of the app may be different for different people - the full steps to find it are in that reddit post.

Other than that, I do still find I have to restart the following services after booting up now that I'm using Ventura, but that might of course be a separate issue:
```bash
sudo brew services restart dnsmasq
brew services restart nginx
```
(Again, on my system I have to do the last one there with a `sudo`, but I suspect that's not correct for most.)

**Comment by gunnie-agency** [comment]
I think the following may have something to do with this as well. If you run `brew services` you get the following notice:
```
Warning: Calling plist_options is deprecated! Use service.require_root instead.
Please report this issue to the elastic/tap tap (not Homebrew/brew or Homebrew/homebrew-core), or even better, submit a PR to fix it:
  /usr/local/Homebrew/Library/Taps/elastic/homebrew-tap/Formula/elasticsearch-full.rb:68
```
My guess is that in the latest update to MacOS Ventura, we cannot use the plist_options anymore and need to use the service.require_root, like the message suggests.

**Comment by K3vinF** [comment]
FYI I recently ran into this issue too. I think it is not related to Valet+, but rather a MacOs bug, see:
https://discussions.apple.com/thread/254341579

Third comment fixed it for me:
Reset using `sfltool resetbtm` from Terminal

**Comment by mischabraam** [comment]
See https://github.com/elastic/homebrew-tap/pull/144#issuecomment-1654074794

**Comment by mischabraam** [comment]
The elasticsearch issue is a non-related issue and fixed in Version 3 using Docker instead of Brew.

The 'background items added' spam is very annoying indeed. Unfortunately not a Valet+ issue or something I can fix. It's macOS related. It seems that the solution provided by @K3vinF (https://github.com/weprovide/valet-plus/issues/617#issuecomment-1663828829) fixes it.
