### ISSUE TITLE
Feature request: Per-Site PHP Versions

### ISSUE THREAD

**Issue by rimple-saini-new** [weprovide/valet-plus#624]
- [x] I've checked the issue queue and could not find anything similar to my feature.
- [x] I'm on the latest version of valet-plus (`valet --version`): `Valet+ 2.4.0-beta6`

**Why implement this feature?**  
By default, Valet uses global PHP installation to serve sites. To support multiple PHP versions across various sites, We need **isolate** and **unisolate** commands to specify which PHP version a particular site should use. The isolate command configures Valet to use the specified PHP version for the site located in your current working directory:

I shall be able to use command for specific site: **valet isolate php@7.4** or any other PHP versions.
To revert a site back to Valet's globally installed PHP version: **valet unisolate**

**What will be required for this feature?**  
CLI Command

**Sources**
All sources related to the feature. If the feature uses external tools like PHP extensions it should at
least contain a link to the tool. Any other media which proves helpful can be included here.

NOTE: This feature already exist under Valet 3.0.0 version
https://github.com/laravel/valet/releases/tag/v3.0.0

**Comment by mischabraam** [comment]
This is supported in 3.x-dev with the `isolate` command, see https://laravel.com/docs/10.x/valet#per-site-php-versions

**Comment by rimple-saini-new** [comment]
@mischabraam  I agree, It is supported in Laravel 3.0, even same has been informed into Issue Description section too. 

**My ask is:** Why this command is not available under **Valet+ 2.4.0-beta6** version ? Is there any way to have this isolate command under **Valet+** ?

**Comment by mischabraam** [comment]
Hi @rimple-saini-new ,
Sorry, I miscommunicated here, my bad.

The isolate command is indeed not available in Valet+ 2.4 and older versions. I'm working on a new version which is a complete rewrite of Valet+. This is version 3 (in the making), which is in the 3.x-dev branch, see https://github.com/weprovide/valet-plus/tree/3.x 
This 3.x version does support the isolate command. Because of the rewrite all commands from Laravel's Valet will automatically be adopted into Valet+ from the 3.x versions and up.
