### ISSUE TITLE
404 Not found 

### ISSUE THREAD

**Issue by felixwerner** [weprovide/valet-plus#638]
when i link a project and the linked folder contains a folder named **public**. i get a _404 - not found_ for the linked url.

**Comment by mischabraam** [comment]
Hi @felixwerner , this can be anything. Without more information I can't trace this to anything.
Did you park your sites root directory? Is there anything in the public directory? Which driver are you trying to use? Which framework? etc.etc.

**Comment by felixwerner** [comment]
Hi mischa thanks for getting back.

it happens on all projects. 

i tested it with a empty project of only a index.php and a empty public folder.
no parked sites, no framework, nothing in the public directory.

the index.php
`<?php echo "hi";`
 
starting out it works. as soon as i add the empty public/ folder i get this 404.

**Comment by mischabraam** [comment]
Hi @felixwerner , this is most likely because of the https://github.com/laravel/valet/blob/master/cli/Valet/Drivers/BasicWithPublicValetDriver.php which is a default driver delivered by Laravel's Valet.

You could write your custom valet driver if you're not using any framework, see https://laravel.com/docs/11.x/valet#custom-valet-drivers
