### ISSUE TITLE
Dnsmasq copy error

### ISSUE THREAD

**Issue by StanSluisveld** [weprovide/valet-plus#64]
Happens when you remove dnsmasq and then reinstall. Should check for existence of the file. Since the file is 100% comments it doesn't have to be included.
```
PHP Warning:  copy(/usr/local/opt/dnsmasq/dnsmasq.conf.example): failed to open stream: No such file or directory in /Users/stanvansluisveld/.composer/vendor/weprovide/valet-plus/cli/Valet/Filesystem.php on line 198

Warning: copy(/usr/local/opt/dnsmasq/dnsmasq.conf.example): failed to open stream: No such file or directory in /Users/stanvansluisveld/.composer/vendor/weprovide/valet-plus/cli/Valet/Filesystem.php on line 198
PHP Warning:  chown(): No such file or directory in /Users/stanvansluisveld/.composer/vendor/weprovide/valet-plus/cli/Valet/Filesystem.php on line 258

Warning: chown(): No such file or directory in /Users/stanvansluisveld/.composer/vendor/weprovide/valet-plus/cli/Valet/Filesystem.php on line 258
PHP Warning:  file_get_contents(/usr/local/etc/dnsmasq.conf): failed to open stream: No such file or directory in /Users/stanvansluisveld/.composer/vendor/weprovide/valet-plus/cli/Valet/Filesystem.php on line 112

Warning: file_get_contents(/usr/local/etc/dnsmasq.conf): failed to open stream: No such file or directory in /Users/stanvansluisveld/.composer/vendor/weprovide/valet-plus/cli/Valet/Filesystem.php on line 112
```

**Comment by Neodork** [comment]
Dear Contributor,

With the release of Valet+ `2.0.0` the Valet+ development team and contributors have implemented the [contribution guidelines](https://github.com/weprovide/valet-plus/blob/master/CONTRIBUTING.md#issue-templates). The contribution guidelines aim to improve the support and workflow of Valet+. For further information why this was implemented please check https://github.com/weprovide/valet-plus/issues/393.

We're closing this ticket because it does not follow the correct format. If you feel your ticket is still relevant we encourage you to re-open your ticket using the [correct format](https://github.com/weprovide/valet-plus/issues/new/choose).

Kind regards,
The Valet+ team
