### ISSUE TITLE
Dnsmasq config location is appended

### ISSUE THREAD

**Issue by StanSluisveld** [weprovide/valet-plus#65]
When you install using one user and switch to another and install again it'll duplicate the line breaking dnsmasq without warnings

**Comment by geerthoeks** [comment]
Located here: `/usr/local/etc/dnsmasq.conf`

**Comment by Neodork** [comment]
Dear Contributor,

With the release of Valet+ `2.0.0` the Valet+ development team and contributors have implemented the [contribution guidelines](https://github.com/weprovide/valet-plus/blob/master/CONTRIBUTING.md#issue-templates). The contribution guidelines aim to improve the support and workflow of Valet+. For further information why this was implemented please check https://github.com/weprovide/valet-plus/issues/393.

We're closing this ticket because it does not follow the correct format. If you feel your ticket is still relevant we encourage you to re-open your ticket using the [correct format](https://github.com/weprovide/valet-plus/issues/new/choose).

Kind regards,
The Valet+ team
