### ISSUE TITLE
date.timezone error, all of a sudden

### ISSUE THREAD

**Issue by kanduvisla** [weprovide/valet-plus#80]
Since this morning I got the following error:

    PHP Warning:  Unknown: Invalid date.timezone value '/var/db/timezone/zoneinfo/Europe/Paris', we selected the timezone 'UTC' for now. in Unknown on line 0

When I looked further, I found that this was caused because the first line of `/usr/local/etc/php/7.0/conf.d/z-performance.ini` was set to this value, and for some reason my PHP version only started complaining about it this morning.

I'm running PHP 7.0 and since last Friday MacOS High Sierra (might that have caused this problem? Didn't have any issues Friday or this weekend for that matter).

Replacing the literal string to `Europe/Amsterdam` solved the issue in my case. But what is the reason that there is an absolute path in that specific file? And for full disclosure: the file it pointed at (`/var/db/timezone/zoneinfo/Europe/Paris`) does exist, so that wasn't the issue.

**Comment by timneutkens** [comment]
Basically we resolve `/etc/localtime`, which is a symlink to a file holding your current timezone data. Then we strip off everything before `Europe/Amsterdam` (or any other timezone) and apply it to the z-performance.ini. This way PHP always has the correct timezone, instead of the standard timezone. In High Sierra they changed the location of the file changed. So I've added the new path 👍 See https://github.com/weprovide/valet-plus/commit/79959085b99470c3ab871b149303d1b6ad2c3820 for the fix 👍
