### ISSUE TITLE
mailhog https

### ISSUE THREAD

**Issue by angeloo** [weprovide/valet-plus#96]
How to setup mailhog with https so it will work with the new chrome version which ask for https with .dev domain?

Thanks

**Comment by samgranger** [comment]
Hi Angeloo,

Please switch to .test instead of .dev.

To do so, please upgrade to the latest version by following these steps:

`composer global update`
`sudo valet domain test`
`valet install`

Then, change all your site configs to reflect the .dev to .test change. Mailhog is now available under mailhog.test
