### ISSUE TITLE
Request: Autosecure default valet provided domains

### ISSUE THREAD

**Issue by MadMikeyB** [weprovide/valet-plus#99]
[In light of the Chrome HSTS change and Valet's change to .test ](https://github.com/laravel/valet/pull/436)- would it be prudent to configure mailhog, elasticsearch and the other valet+ provided tools to be automatically secure for backward compatibilities sake?

I know that if you opt to use `.dev` rather than `.test` then you run the risk of domain name collisions, however many people will still use `.dev` for backwards compatibility purposes. Moving to `.test` by default could be considered a breaking change (though I understand why it is necessary).

For example, I have around 50 SSL .dev domains using valet+, and while I am moving them all over to `.test` it is rather annoying to visit projectname.test and be slapped with the SSL warning as it was previously using SSL on the .dev domain name and there isn't a valid certificate on my machine for the `.test` variant.

Additionally it could be considered good practise to have these default services provided over HTTPS regardless of gTLD used.

Just probing interest for this, if there is I'd be happy to attempt to tackle a PR for this (I imagine it'd be the equivalent of running `valet secure mailhog && valet secure elasticsearch` programmatically on `valet install`).

**Comment by SanderAtom** [comment]
I agree securing mailhog and elasticsearch by default would be nice. Maybe it's even possible to update the SSL certificates when you change the gTLD with `sudo valet domain test`?

**Comment by Neodork** [comment]
Dear Contributor,

With the release of Valet+ `2.0.0` the Valet+ development team and contributors have implemented the [contribution guidelines](https://github.com/weprovide/valet-plus/blob/master/CONTRIBUTING.md#issue-templates). The contribution guidelines aim to improve the support and workflow of Valet+. For further information why this was implemented please check https://github.com/weprovide/valet-plus/issues/393.

We're closing this ticket because it does not follow the correct format. If you feel your ticket is still relevant we encourage you to re-open your ticket using the [correct format](https://github.com/weprovide/valet-plus/issues/new/choose).

Kind regards,
The Valet+ team
